/*
 * generated by Xtext 2.35.0
 */
package semcomdt.swarchitecture.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import semcomdt.swarchitecture.ide.contentassist.antlr.internal.InternalCbseParser;
import semcomdt.swarchitecture.services.CbseGrammarAccess;

public class CbseParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(CbseGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, CbseGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getElementAccess().getAlternatives(), "rule__Element__Alternatives");
			builder.put(grammarAccess.getComponentAccess().getAlternatives(), "rule__Component__Alternatives");
			builder.put(grammarAccess.getPortKindAccess().getAlternatives(), "rule__PortKind__Alternatives");
			builder.put(grammarAccess.getArchitectureElementTypeAccess().getAlternatives(), "rule__ArchitectureElementType__Alternatives");
			builder.put(grammarAccess.getConnectorAccess().getGroup(), "rule__Connector__Group__0");
			builder.put(grammarAccess.getPortAccess().getGroup(), "rule__Port__Group__0");
			builder.put(grammarAccess.getPortAccess().getGroup_4(), "rule__Port__Group_4__0");
			builder.put(grammarAccess.getPassiveComponentAccess().getGroup(), "rule__PassiveComponent__Group__0");
			builder.put(grammarAccess.getActiveComponentAccess().getGroup(), "rule__ActiveComponent__Group__0");
			builder.put(grammarAccess.getFunctionAccess().getGroup(), "rule__Function__Group__0");
			builder.put(grammarAccess.getInteractionNatureAccess().getGroup(), "rule__InteractionNature__Group__0");
			builder.put(grammarAccess.getDataAccess().getGroup(), "rule__Data__Group__0");
			builder.put(grammarAccess.getDataAccess().getGroup_2(), "rule__Data__Group_2__0");
			builder.put(grammarAccess.getDataTypeAccess().getGroup(), "rule__DataType__Group__0");
			builder.put(grammarAccess.getPayloadAccess().getGroup(), "rule__Payload__Group__0");
			builder.put(grammarAccess.getMsgExchangeAccess().getGroup(), "rule__MsgExchange__Group__0");
			builder.put(grammarAccess.getCommunicationStyleAccess().getGroup(), "rule__CommunicationStyle__Group__0");
			builder.put(grammarAccess.getCbseAccess().getSystemAssignment(), "rule__Cbse__SystemAssignment");
			builder.put(grammarAccess.getConnectorAccess().getNameAssignment_1(), "rule__Connector__NameAssignment_1");
			builder.put(grammarAccess.getPortAccess().getNameAssignment_1(), "rule__Port__NameAssignment_1");
			builder.put(grammarAccess.getPortAccess().getKindAssignment_3(), "rule__Port__KindAssignment_3");
			builder.put(grammarAccess.getPortAccess().getInteractionNatureAssignment_4_1(), "rule__Port__InteractionNatureAssignment_4_1");
			builder.put(grammarAccess.getPassiveComponentAccess().getNameAssignment_1(), "rule__PassiveComponent__NameAssignment_1");
			builder.put(grammarAccess.getActiveComponentAccess().getNameAssignment_1(), "rule__ActiveComponent__NameAssignment_1");
			builder.put(grammarAccess.getActiveComponentAccess().getFunctionsAssignment_3(), "rule__ActiveComponent__FunctionsAssignment_3");
			builder.put(grammarAccess.getFunctionAccess().getNameAssignment_1(), "rule__Function__NameAssignment_1");
			builder.put(grammarAccess.getInteractionNatureAccess().getNameAssignment_1(), "rule__InteractionNature__NameAssignment_1");
			builder.put(grammarAccess.getDataAccess().getNameAssignment_1(), "rule__Data__NameAssignment_1");
			builder.put(grammarAccess.getDataAccess().getSuperTypeAssignment_2_1(), "rule__Data__SuperTypeAssignment_2_1");
			builder.put(grammarAccess.getDataTypeAccess().getNameAssignment_1(), "rule__DataType__NameAssignment_1");
			builder.put(grammarAccess.getPayloadAccess().getNameAssignment_1(), "rule__Payload__NameAssignment_1");
			builder.put(grammarAccess.getMsgExchangeAccess().getNameAssignment_1(), "rule__MsgExchange__NameAssignment_1");
			builder.put(grammarAccess.getCommunicationStyleAccess().getNameAssignment_1(), "rule__CommunicationStyle__NameAssignment_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private CbseGrammarAccess grammarAccess;

	@Override
	protected InternalCbseParser createParser() {
		InternalCbseParser result = new InternalCbseParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public CbseGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CbseGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
