/**
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity.ssrt;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link semcomdt.swsecurity.ssrt.Element#getName <em>Name</em>}</li>
 *   <li>{@link semcomdt.swsecurity.ssrt.Element#getRefines <em>Refines</em>}</li>
 *   <li>{@link semcomdt.swsecurity.ssrt.Element#getDefinition <em>Definition</em>}</li>
 *   <li>{@link semcomdt.swsecurity.ssrt.Element#getSource <em>Source</em>}</li>
 * </ul>
 *
 * @see semcomdt.swsecurity.ssrt.SsrtPackage#getElement()
 * @model
 * @generated
 */
public interface Element extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see semcomdt.swsecurity.ssrt.SsrtPackage#getElement_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link semcomdt.swsecurity.ssrt.Element#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Refines</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Refines</em>' reference.
   * @see #setRefines(Element)
   * @see semcomdt.swsecurity.ssrt.SsrtPackage#getElement_Refines()
   * @model
   * @generated
   */
  Element getRefines();

  /**
   * Sets the value of the '{@link semcomdt.swsecurity.ssrt.Element#getRefines <em>Refines</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Refines</em>' reference.
   * @see #getRefines()
   * @generated
   */
  void setRefines(Element value);

  /**
   * Returns the value of the '<em><b>Definition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Definition</em>' attribute.
   * @see #setDefinition(String)
   * @see semcomdt.swsecurity.ssrt.SsrtPackage#getElement_Definition()
   * @model
   * @generated
   */
  String getDefinition();

  /**
   * Sets the value of the '{@link semcomdt.swsecurity.ssrt.Element#getDefinition <em>Definition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Definition</em>' attribute.
   * @see #getDefinition()
   * @generated
   */
  void setDefinition(String value);

  /**
   * Returns the value of the '<em><b>Source</b></em>' containment reference list.
   * The list contents are of type {@link semcomdt.swsecurity.ssrt.Relation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' containment reference list.
   * @see semcomdt.swsecurity.ssrt.SsrtPackage#getElement_Source()
   * @model containment="true"
   * @generated
   */
  EList<Relation> getSource();

} // Element
