/*
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity.objective.ciaamps.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import semcomdt.swsecurity.objective.ciaamps.CiaampsRuntimeModule;
import semcomdt.swsecurity.objective.ciaamps.CiaampsStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CiaampsIdeSetup extends CiaampsStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CiaampsRuntimeModule(), new CiaampsIdeModule()));
	}
	
}
