/*
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity.objective.ide;


/**
 * Use this class to register ide components.
 */
public class CiaampsIdeModule extends AbstractCiaampsIdeModule {
}
