/*
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity.objective.ciaamps.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import semcomdt.swsecurity.objective.ciaamps.xtext.ui.internal.XtextActivator;

public class CiaampsUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("semcomdt.swsecurity.objective.ciaamps.Ciaamps");
	}

}
