/*
 * generated by Xtext 2.35.0
 */
package semcomdt.swarchitecture.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import semcomdt.swarchitecture.parser.antlr.internal.InternalCbseParser;
import semcomdt.swarchitecture.services.CbseGrammarAccess;

public class CbseParser extends AbstractAntlrParser {

	@Inject
	private CbseGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCbseParser createParser(XtextTokenStream stream) {
		return new InternalCbseParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Cbse";
	}

	public CbseGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CbseGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
