/*
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import semcomdt.swsecurity.services.SsrtGrammarAccess;
import semcomdt.swsecurity.ssrt.Model;
import semcomdt.swsecurity.ssrt.Relation;
import semcomdt.swsecurity.ssrt.Solution;
import semcomdt.swsecurity.ssrt.SolutionElement;
import semcomdt.swsecurity.ssrt.SolutionTree;
import semcomdt.swsecurity.ssrt.SsrtPackage;

@SuppressWarnings("all")
public class SsrtSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private SsrtGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == SsrtPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case SsrtPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case SsrtPackage.RELATION:
				sequence_Relation(context, (Relation) semanticObject); 
				return; 
			case SsrtPackage.SOLUTION:
				sequence_Solution(context, (Solution) semanticObject); 
				return; 
			case SsrtPackage.SOLUTION_ELEMENT:
				sequence_SolutionElement(context, (SolutionElement) semanticObject); 
				return; 
			case SsrtPackage.SOLUTION_TREE:
				sequence_SolutionTree(context, (SolutionTree) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     solutiontrees+=SolutionTree+
	 * </pre>
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Relation returns Relation
	 *
	 * Constraint:
	 *     (name=ID target=[SolutionElement|QualifiedName])
	 * </pre>
	 */
	protected void sequence_Relation(ISerializationContext context, Relation semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SsrtPackage.Literals.RELATION__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SsrtPackage.Literals.RELATION__NAME));
			if (transientValues.isValueTransient(semanticObject, SsrtPackage.Literals.RELATION__TARGET) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SsrtPackage.Literals.RELATION__TARGET));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRelationAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getRelationAccess().getTargetSolutionElementQualifiedNameParserRuleCall_2_0_1(), semanticObject.eGet(SsrtPackage.Literals.RELATION__TARGET, false));
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     SolutionElement returns SolutionElement
	 *
	 * Constraint:
	 *     (name=ID refines=[SolutionElement|QualifiedName]? definition=STRING source+=Relation*)
	 * </pre>
	 */
	protected void sequence_SolutionElement(ISerializationContext context, SolutionElement semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     SolutionTree returns SolutionTree
	 *
	 * Constraint:
	 *     (name=ID contributesTo+=[SecurityProperty|QualifiedName] provides+=Solution*)
	 * </pre>
	 */
	protected void sequence_SolutionTree(ISerializationContext context, SolutionTree semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Solution returns Solution
	 *
	 * Constraint:
	 *     (kind=SolutionType level=Level name=ID refines+=[Solution|QualifiedName]* solutionelements+=SolutionElement*)
	 * </pre>
	 */
	protected void sequence_Solution(ISerializationContext context, Solution semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
