/**
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity.objective.ciaamps.ciaamps;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Security Property</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see semcomdt.swsecurity.objective.ciaamps.ciaamps.CiaampsPackage#getSecurityProperty()
 * @model
 * @generated
 */
public interface SecurityProperty extends AssetDetails
{
} // SecurityProperty
