/*
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import semcomdt.swsecurity.ide.contentassist.antlr.internal.InternalSsrtParser;
import semcomdt.swsecurity.services.SsrtGrammarAccess;

public class SsrtParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(SsrtGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, SsrtGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getLevelAccess().getAlternatives(), "rule__Level__Alternatives");
			builder.put(grammarAccess.getSolutionTypeAccess().getAlternatives(), "rule__SolutionType__Alternatives");
			builder.put(grammarAccess.getSolutionTreeAccess().getGroup(), "rule__SolutionTree__Group__0");
			builder.put(grammarAccess.getSolutionAccess().getGroup(), "rule__Solution__Group__0");
			builder.put(grammarAccess.getSolutionAccess().getGroup_3(), "rule__Solution__Group_3__0");
			builder.put(grammarAccess.getElementAccess().getGroup(), "rule__Element__Group__0");
			builder.put(grammarAccess.getElementAccess().getGroup_2(), "rule__Element__Group_2__0");
			builder.put(grammarAccess.getRelationAccess().getGroup(), "rule__Relation__Group__0");
			builder.put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
			builder.put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
			builder.put(grammarAccess.getModelAccess().getSolutiontreesAssignment(), "rule__Model__SolutiontreesAssignment");
			builder.put(grammarAccess.getSolutionTreeAccess().getNameAssignment_1(), "rule__SolutionTree__NameAssignment_1");
			builder.put(grammarAccess.getSolutionTreeAccess().getContributesToAssignment_3(), "rule__SolutionTree__ContributesToAssignment_3");
			builder.put(grammarAccess.getSolutionTreeAccess().getProvidesAssignment_5(), "rule__SolutionTree__ProvidesAssignment_5");
			builder.put(grammarAccess.getSolutionAccess().getKindAssignment_0(), "rule__Solution__KindAssignment_0");
			builder.put(grammarAccess.getSolutionAccess().getLevelAssignment_1(), "rule__Solution__LevelAssignment_1");
			builder.put(grammarAccess.getSolutionAccess().getNameAssignment_2(), "rule__Solution__NameAssignment_2");
			builder.put(grammarAccess.getSolutionAccess().getRefinesAssignment_3_1(), "rule__Solution__RefinesAssignment_3_1");
			builder.put(grammarAccess.getSolutionAccess().getSolutionelementsAssignment_5(), "rule__Solution__SolutionelementsAssignment_5");
			builder.put(grammarAccess.getElementAccess().getNameAssignment_1(), "rule__Element__NameAssignment_1");
			builder.put(grammarAccess.getElementAccess().getRefinesAssignment_2_1(), "rule__Element__RefinesAssignment_2_1");
			builder.put(grammarAccess.getElementAccess().getDefinitionAssignment_4(), "rule__Element__DefinitionAssignment_4");
			builder.put(grammarAccess.getElementAccess().getSourceAssignment_6(), "rule__Element__SourceAssignment_6");
			builder.put(grammarAccess.getRelationAccess().getNameAssignment_1(), "rule__Relation__NameAssignment_1");
			builder.put(grammarAccess.getRelationAccess().getTargetAssignment_2(), "rule__Relation__TargetAssignment_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private SsrtGrammarAccess grammarAccess;

	@Override
	protected InternalSsrtParser createParser() {
		InternalSsrtParser result = new InternalSsrtParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public SsrtGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SsrtGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
