/*
 * generated by Xtext 2.35.0
 */
package semcomdt.swarchitecture.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import semcomdt.swarchitecture.CbseRuntimeModule;
import semcomdt.swarchitecture.CbseStandaloneSetup;
import semcomdt.swarchitecture.ide.CbseIdeModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class CbseWebSetup extends CbseStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CbseRuntimeModule(), new CbseIdeModule(), new CbseWebModule()));
	}
	
}
