/*
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class SsrtGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "semcomdt.swsecurity.Ssrt.Model");
		private final Assignment cSolutiontreesAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cSolutiontreesSolutionTreeParserRuleCall_0 = (RuleCall)cSolutiontreesAssignment.eContents().get(0);
		
		//Model:
		//    solutiontrees+=SolutionTree*;
		@Override public ParserRule getRule() { return rule; }
		
		//solutiontrees+=SolutionTree*
		public Assignment getSolutiontreesAssignment() { return cSolutiontreesAssignment; }
		
		//SolutionTree
		public RuleCall getSolutiontreesSolutionTreeParserRuleCall_0() { return cSolutiontreesSolutionTreeParserRuleCall_0; }
	}
	public class SolutionTreeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "semcomdt.swsecurity.Ssrt.SolutionTree");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSolutionTreeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cContributesToKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cContributesToAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cContributesToSecurityPropertyCrossReference_3_0 = (CrossReference)cContributesToAssignment_3.eContents().get(0);
		private final RuleCall cContributesToSecurityPropertyQualifiedNameParserRuleCall_3_0_1 = (RuleCall)cContributesToSecurityPropertyCrossReference_3_0.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cSolutionAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cSolutionSolutionParserRuleCall_5_0 = (RuleCall)cSolutionAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//SolutionTree:
		//    'SolutionTree' name=ID "contributesTo" contributesTo+=[ciaamps::SecurityProperty|QualifiedName]
		//     '{' solution+=Solution* '}'
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//'SolutionTree' name=ID "contributesTo" contributesTo+=[ciaamps::SecurityProperty|QualifiedName]
		// '{' solution+=Solution* '}'
		public Group getGroup() { return cGroup; }
		
		//'SolutionTree'
		public Keyword getSolutionTreeKeyword_0() { return cSolutionTreeKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//"contributesTo"
		public Keyword getContributesToKeyword_2() { return cContributesToKeyword_2; }
		
		//contributesTo+=[ciaamps::SecurityProperty|QualifiedName]
		public Assignment getContributesToAssignment_3() { return cContributesToAssignment_3; }
		
		//[ciaamps::SecurityProperty|QualifiedName]
		public CrossReference getContributesToSecurityPropertyCrossReference_3_0() { return cContributesToSecurityPropertyCrossReference_3_0; }
		
		//QualifiedName
		public RuleCall getContributesToSecurityPropertyQualifiedNameParserRuleCall_3_0_1() { return cContributesToSecurityPropertyQualifiedNameParserRuleCall_3_0_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//solution+=Solution*
		public Assignment getSolutionAssignment_5() { return cSolutionAssignment_5; }
		
		//Solution
		public RuleCall getSolutionSolutionParserRuleCall_5_0() { return cSolutionSolutionParserRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class SolutionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "semcomdt.swsecurity.Ssrt.Solution");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cKindAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cKindSSTSolutionKindEnumRuleCall_0_0 = (RuleCall)cKindAssignment_0.eContents().get(0);
		private final Assignment cLevelAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cLevelSSTLevelEnumRuleCall_1_0 = (RuleCall)cLevelAssignment_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cRefinesKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cRefinesAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cRefinesSolutionCrossReference_3_1_0 = (CrossReference)cRefinesAssignment_3_1.eContents().get(0);
		private final RuleCall cRefinesSolutionQualifiedNameParserRuleCall_3_1_0_1 = (RuleCall)cRefinesSolutionCrossReference_3_1_0.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cConceptsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cConceptsSolutionElementParserRuleCall_5_0 = (RuleCall)cConceptsAssignment_5.eContents().get(0);
		private final Assignment cRelationsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cRelationsRelationParserRuleCall_6_0 = (RuleCall)cRelationsAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Solution :
		//    kind=SSTSolutionKind level=SSTLevel name=ID
		//    ("refines" refines+=[Solution|QualifiedName]*)?
		//    "{" concepts+=SolutionElement*
		//    relations+=Relation* "}"
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//kind=SSTSolutionKind level=SSTLevel name=ID
		//("refines" refines+=[Solution|QualifiedName]*)?
		//"{" concepts+=SolutionElement*
		//relations+=Relation* "}"
		public Group getGroup() { return cGroup; }
		
		//kind=SSTSolutionKind
		public Assignment getKindAssignment_0() { return cKindAssignment_0; }
		
		//SSTSolutionKind
		public RuleCall getKindSSTSolutionKindEnumRuleCall_0_0() { return cKindSSTSolutionKindEnumRuleCall_0_0; }
		
		//level=SSTLevel
		public Assignment getLevelAssignment_1() { return cLevelAssignment_1; }
		
		//SSTLevel
		public RuleCall getLevelSSTLevelEnumRuleCall_1_0() { return cLevelSSTLevelEnumRuleCall_1_0; }
		
		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
		
		//("refines" refines+=[Solution|QualifiedName]*)?
		public Group getGroup_3() { return cGroup_3; }
		
		//"refines"
		public Keyword getRefinesKeyword_3_0() { return cRefinesKeyword_3_0; }
		
		//refines+=[Solution|QualifiedName]*
		public Assignment getRefinesAssignment_3_1() { return cRefinesAssignment_3_1; }
		
		//[Solution|QualifiedName]
		public CrossReference getRefinesSolutionCrossReference_3_1_0() { return cRefinesSolutionCrossReference_3_1_0; }
		
		//QualifiedName
		public RuleCall getRefinesSolutionQualifiedNameParserRuleCall_3_1_0_1() { return cRefinesSolutionQualifiedNameParserRuleCall_3_1_0_1; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//concepts+=SolutionElement*
		public Assignment getConceptsAssignment_5() { return cConceptsAssignment_5; }
		
		//SolutionElement
		public RuleCall getConceptsSolutionElementParserRuleCall_5_0() { return cConceptsSolutionElementParserRuleCall_5_0; }
		
		//relations+=Relation*
		public Assignment getRelationsAssignment_6() { return cRelationsAssignment_6; }
		
		//Relation
		public RuleCall getRelationsRelationParserRuleCall_6_0() { return cRelationsRelationParserRuleCall_6_0; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class SolutionElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "semcomdt.swsecurity.Ssrt.SolutionElement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSolutionElementKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cRefinesKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cRefinesAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final CrossReference cRefinesSolutionElementCrossReference_2_1_0 = (CrossReference)cRefinesAssignment_2_1.eContents().get(0);
		private final RuleCall cRefinesSolutionElementQualifiedNameParserRuleCall_2_1_0_1 = (RuleCall)cRefinesSolutionElementCrossReference_2_1_0.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cDefinitionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDefinitionSTRINGTerminalRuleCall_4_0 = (RuleCall)cDefinitionAssignment_4.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//SolutionElement:
		//    "Solution Element" name=ID ("refines" refines=[SolutionElement|QualifiedName])?
		//    "(" definition=STRING ")"
		////    ("-"relation+=STRING">" relatedconcept+=[Concept|QualifiedName])?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"Solution Element" name=ID ("refines" refines=[SolutionElement|QualifiedName])?
		//"(" definition=STRING ")"
		public Group getGroup() { return cGroup; }
		
		//"Solution Element"
		public Keyword getSolutionElementKeyword_0() { return cSolutionElementKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//("refines" refines=[SolutionElement|QualifiedName])?
		public Group getGroup_2() { return cGroup_2; }
		
		//"refines"
		public Keyword getRefinesKeyword_2_0() { return cRefinesKeyword_2_0; }
		
		//refines=[SolutionElement|QualifiedName]
		public Assignment getRefinesAssignment_2_1() { return cRefinesAssignment_2_1; }
		
		//[SolutionElement|QualifiedName]
		public CrossReference getRefinesSolutionElementCrossReference_2_1_0() { return cRefinesSolutionElementCrossReference_2_1_0; }
		
		//QualifiedName
		public RuleCall getRefinesSolutionElementQualifiedNameParserRuleCall_2_1_0_1() { return cRefinesSolutionElementQualifiedNameParserRuleCall_2_1_0_1; }
		
		//"("
		public Keyword getLeftParenthesisKeyword_3() { return cLeftParenthesisKeyword_3; }
		
		//definition=STRING
		public Assignment getDefinitionAssignment_4() { return cDefinitionAssignment_4; }
		
		//STRING
		public RuleCall getDefinitionSTRINGTerminalRuleCall_4_0() { return cDefinitionSTRINGTerminalRuleCall_4_0; }
		
		//")"
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }
	}
	public class RelationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "semcomdt.swsecurity.Ssrt.Relation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRelationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cRefinesKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cRefinesAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final CrossReference cRefinesRelationCrossReference_2_1_0 = (CrossReference)cRefinesAssignment_2_1.eContents().get(0);
		private final RuleCall cRefinesRelationQualifiedNameParserRuleCall_2_1_0_1 = (RuleCall)cRefinesRelationCrossReference_2_1_0.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cDefinitionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDefinitionSTRINGTerminalRuleCall_4_0 = (RuleCall)cDefinitionAssignment_4.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cInAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cInSolutionElementCrossReference_6_0 = (CrossReference)cInAssignment_6.eContents().get(0);
		private final RuleCall cInSolutionElementQualifiedNameParserRuleCall_6_0_1 = (RuleCall)cInSolutionElementCrossReference_6_0.eContents().get(1);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cOutAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final CrossReference cOutSolutionElementCrossReference_8_0 = (CrossReference)cOutAssignment_8.eContents().get(0);
		private final RuleCall cOutSolutionElementQualifiedNameParserRuleCall_8_0_1 = (RuleCall)cOutSolutionElementCrossReference_8_0.eContents().get(1);
		
		//Relation :
		//    "Relation" name=ID ("refines" refines=[Relation|QualifiedName])?
		//    "(" definition=STRING ")"
		//    in=[SolutionElement|QualifiedName] "->" out=[SolutionElement|QualifiedName]
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"Relation" name=ID ("refines" refines=[Relation|QualifiedName])?
		//"(" definition=STRING ")"
		//in=[SolutionElement|QualifiedName] "->" out=[SolutionElement|QualifiedName]
		public Group getGroup() { return cGroup; }
		
		//"Relation"
		public Keyword getRelationKeyword_0() { return cRelationKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//("refines" refines=[Relation|QualifiedName])?
		public Group getGroup_2() { return cGroup_2; }
		
		//"refines"
		public Keyword getRefinesKeyword_2_0() { return cRefinesKeyword_2_0; }
		
		//refines=[Relation|QualifiedName]
		public Assignment getRefinesAssignment_2_1() { return cRefinesAssignment_2_1; }
		
		//[Relation|QualifiedName]
		public CrossReference getRefinesRelationCrossReference_2_1_0() { return cRefinesRelationCrossReference_2_1_0; }
		
		//QualifiedName
		public RuleCall getRefinesRelationQualifiedNameParserRuleCall_2_1_0_1() { return cRefinesRelationQualifiedNameParserRuleCall_2_1_0_1; }
		
		//"("
		public Keyword getLeftParenthesisKeyword_3() { return cLeftParenthesisKeyword_3; }
		
		//definition=STRING
		public Assignment getDefinitionAssignment_4() { return cDefinitionAssignment_4; }
		
		//STRING
		public RuleCall getDefinitionSTRINGTerminalRuleCall_4_0() { return cDefinitionSTRINGTerminalRuleCall_4_0; }
		
		//")"
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }
		
		//in=[SolutionElement|QualifiedName]
		public Assignment getInAssignment_6() { return cInAssignment_6; }
		
		//[SolutionElement|QualifiedName]
		public CrossReference getInSolutionElementCrossReference_6_0() { return cInSolutionElementCrossReference_6_0; }
		
		//QualifiedName
		public RuleCall getInSolutionElementQualifiedNameParserRuleCall_6_0_1() { return cInSolutionElementQualifiedNameParserRuleCall_6_0_1; }
		
		//"->"
		public Keyword getHyphenMinusGreaterThanSignKeyword_7() { return cHyphenMinusGreaterThanSignKeyword_7; }
		
		//out=[SolutionElement|QualifiedName]
		public Assignment getOutAssignment_8() { return cOutAssignment_8; }
		
		//[SolutionElement|QualifiedName]
		public CrossReference getOutSolutionElementCrossReference_8_0() { return cOutSolutionElementCrossReference_8_0; }
		
		//QualifiedName
		public RuleCall getOutSolutionElementQualifiedNameParserRuleCall_8_0_1() { return cOutSolutionElementQualifiedNameParserRuleCall_8_0_1; }
	}
	public class QualifiedNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "semcomdt.swsecurity.Ssrt.QualifiedName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//QualifiedName:
		//    ID ('.' ID)*;
		@Override public ParserRule getRule() { return rule; }
		
		//ID ('.' ID)*
		public Group getGroup() { return cGroup; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }
		
		//('.' ID)*
		public Group getGroup_1() { return cGroup_1; }
		
		//'.'
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}
	
	public class SSTLevelElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "semcomdt.swsecurity.Ssrt.SSTLevel");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cConceptualEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cConceptualConceptualKeyword_0_0 = (Keyword)cConceptualEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cDesignEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cDesignDesignKeyword_1_0 = (Keyword)cDesignEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cRealizationEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cRealizationRealizationKeyword_2_0 = (Keyword)cRealizationEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum SSTLevel :
		//    Conceptual="Conceptual" | Design="Design" | Realization="Realization"
		//;
		public EnumRule getRule() { return rule; }
		
		//Conceptual="Conceptual" | Design="Design" | Realization="Realization"
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Conceptual="Conceptual"
		public EnumLiteralDeclaration getConceptualEnumLiteralDeclaration_0() { return cConceptualEnumLiteralDeclaration_0; }
		
		//"Conceptual"
		public Keyword getConceptualConceptualKeyword_0_0() { return cConceptualConceptualKeyword_0_0; }
		
		//Design="Design"
		public EnumLiteralDeclaration getDesignEnumLiteralDeclaration_1() { return cDesignEnumLiteralDeclaration_1; }
		
		//"Design"
		public Keyword getDesignDesignKeyword_1_0() { return cDesignDesignKeyword_1_0; }
		
		//Realization="Realization"
		public EnumLiteralDeclaration getRealizationEnumLiteralDeclaration_2() { return cRealizationEnumLiteralDeclaration_2; }
		
		//"Realization"
		public Keyword getRealizationRealizationKeyword_2_0() { return cRealizationRealizationKeyword_2_0; }
	}
	public class SSTSolutionKindElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "semcomdt.swsecurity.Ssrt.SSTSolutionKind");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cSecurityPatternEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cSecurityPatternSecurityPatternKeyword_0_0 = (Keyword)cSecurityPatternEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cTacticEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cTacticTacticKeyword_1_0 = (Keyword)cTacticEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum SSTSolutionKind :
		//    SecurityPattern="SecurityPattern" | Tactic="Tactic"
		//;
		public EnumRule getRule() { return rule; }
		
		//SecurityPattern="SecurityPattern" | Tactic="Tactic"
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//SecurityPattern="SecurityPattern"
		public EnumLiteralDeclaration getSecurityPatternEnumLiteralDeclaration_0() { return cSecurityPatternEnumLiteralDeclaration_0; }
		
		//"SecurityPattern"
		public Keyword getSecurityPatternSecurityPatternKeyword_0_0() { return cSecurityPatternSecurityPatternKeyword_0_0; }
		
		//Tactic="Tactic"
		public EnumLiteralDeclaration getTacticEnumLiteralDeclaration_1() { return cTacticEnumLiteralDeclaration_1; }
		
		//"Tactic"
		public Keyword getTacticTacticKeyword_1_0() { return cTacticTacticKeyword_1_0; }
	}
	
	private final ModelElements pModel;
	private final SolutionTreeElements pSolutionTree;
	private final SolutionElements pSolution;
	private final SolutionElementElements pSolutionElement;
	private final RelationElements pRelation;
	private final SSTLevelElements eSSTLevel;
	private final SSTSolutionKindElements eSSTSolutionKind;
	private final QualifiedNameElements pQualifiedName;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public SsrtGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pSolutionTree = new SolutionTreeElements();
		this.pSolution = new SolutionElements();
		this.pSolutionElement = new SolutionElementElements();
		this.pRelation = new RelationElements();
		this.eSSTLevel = new SSTLevelElements();
		this.eSSTSolutionKind = new SSTSolutionKindElements();
		this.pQualifiedName = new QualifiedNameElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("semcomdt.swsecurity.Ssrt".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//    solutiontrees+=SolutionTree*;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//SolutionTree:
	//    'SolutionTree' name=ID "contributesTo" contributesTo+=[ciaamps::SecurityProperty|QualifiedName]
	//     '{' solution+=Solution* '}'
	//    ;
	public SolutionTreeElements getSolutionTreeAccess() {
		return pSolutionTree;
	}
	
	public ParserRule getSolutionTreeRule() {
		return getSolutionTreeAccess().getRule();
	}
	
	//Solution :
	//    kind=SSTSolutionKind level=SSTLevel name=ID
	//    ("refines" refines+=[Solution|QualifiedName]*)?
	//    "{" concepts+=SolutionElement*
	//    relations+=Relation* "}"
	//;
	public SolutionElements getSolutionAccess() {
		return pSolution;
	}
	
	public ParserRule getSolutionRule() {
		return getSolutionAccess().getRule();
	}
	
	//SolutionElement:
	//    "Solution Element" name=ID ("refines" refines=[SolutionElement|QualifiedName])?
	//    "(" definition=STRING ")"
	////    ("-"relation+=STRING">" relatedconcept+=[Concept|QualifiedName])?
	//;
	public SolutionElementElements getSolutionElementAccess() {
		return pSolutionElement;
	}
	
	public ParserRule getSolutionElementRule() {
		return getSolutionElementAccess().getRule();
	}
	
	//Relation :
	//    "Relation" name=ID ("refines" refines=[Relation|QualifiedName])?
	//    "(" definition=STRING ")"
	//    in=[SolutionElement|QualifiedName] "->" out=[SolutionElement|QualifiedName]
	//;
	public RelationElements getRelationAccess() {
		return pRelation;
	}
	
	public ParserRule getRelationRule() {
		return getRelationAccess().getRule();
	}
	
	//enum SSTLevel :
	//    Conceptual="Conceptual" | Design="Design" | Realization="Realization"
	//;
	public SSTLevelElements getSSTLevelAccess() {
		return eSSTLevel;
	}
	
	public EnumRule getSSTLevelRule() {
		return getSSTLevelAccess().getRule();
	}
	
	//enum SSTSolutionKind :
	//    SecurityPattern="SecurityPattern" | Tactic="Tactic"
	//;
	public SSTSolutionKindElements getSSTSolutionKindAccess() {
		return eSSTSolutionKind;
	}
	
	public EnumRule getSSTSolutionKindRule() {
		return getSSTSolutionKindAccess().getRule();
	}
	
	//QualifiedName:
	//    ID ('.' ID)*;
	public QualifiedNameElements getQualifiedNameAccess() {
		return pQualifiedName;
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
