/*
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity.objective.ciaamps.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCiaampsScopeProvider extends DelegatingScopeProvider {
}
