/*
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity.objective.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CiaampsUiModule extends AbstractCiaampsUiModule {

	public CiaampsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
