/*
 * generated by Xtext 2.35.0
 */
package semcomdt.swarchitecture.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class CbseAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("semcomdt/swarchitecture/parser/antlr/internal/InternalCbse.tokens");
	}
}
