/**
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity.ssrt;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Relation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link semcomdt.swsecurity.ssrt.Relation#getName <em>Name</em>}</li>
 *   <li>{@link semcomdt.swsecurity.ssrt.Relation#getRefines <em>Refines</em>}</li>
 *   <li>{@link semcomdt.swsecurity.ssrt.Relation#getDefinition <em>Definition</em>}</li>
 *   <li>{@link semcomdt.swsecurity.ssrt.Relation#getIn <em>In</em>}</li>
 *   <li>{@link semcomdt.swsecurity.ssrt.Relation#getOut <em>Out</em>}</li>
 * </ul>
 *
 * @see semcomdt.swsecurity.ssrt.SsrtPackage#getRelation()
 * @model
 * @generated
 */
public interface Relation extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see semcomdt.swsecurity.ssrt.SsrtPackage#getRelation_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link semcomdt.swsecurity.ssrt.Relation#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Refines</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Refines</em>' reference.
   * @see #setRefines(Relation)
   * @see semcomdt.swsecurity.ssrt.SsrtPackage#getRelation_Refines()
   * @model
   * @generated
   */
  Relation getRefines();

  /**
   * Sets the value of the '{@link semcomdt.swsecurity.ssrt.Relation#getRefines <em>Refines</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Refines</em>' reference.
   * @see #getRefines()
   * @generated
   */
  void setRefines(Relation value);

  /**
   * Returns the value of the '<em><b>Definition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Definition</em>' attribute.
   * @see #setDefinition(String)
   * @see semcomdt.swsecurity.ssrt.SsrtPackage#getRelation_Definition()
   * @model
   * @generated
   */
  String getDefinition();

  /**
   * Sets the value of the '{@link semcomdt.swsecurity.ssrt.Relation#getDefinition <em>Definition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Definition</em>' attribute.
   * @see #getDefinition()
   * @generated
   */
  void setDefinition(String value);

  /**
   * Returns the value of the '<em><b>In</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>In</em>' reference.
   * @see #setIn(SolutionElement)
   * @see semcomdt.swsecurity.ssrt.SsrtPackage#getRelation_In()
   * @model
   * @generated
   */
  SolutionElement getIn();

  /**
   * Sets the value of the '{@link semcomdt.swsecurity.ssrt.Relation#getIn <em>In</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>In</em>' reference.
   * @see #getIn()
   * @generated
   */
  void setIn(SolutionElement value);

  /**
   * Returns the value of the '<em><b>Out</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Out</em>' reference.
   * @see #setOut(SolutionElement)
   * @see semcomdt.swsecurity.ssrt.SsrtPackage#getRelation_Out()
   * @model
   * @generated
   */
  SolutionElement getOut();

  /**
   * Sets the value of the '{@link semcomdt.swsecurity.ssrt.Relation#getOut <em>Out</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Out</em>' reference.
   * @see #getOut()
   * @generated
   */
  void setOut(SolutionElement value);

} // Relation
