/**
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity.ssrt;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Relation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link semcomdt.swsecurity.ssrt.Relation#getName <em>Name</em>}</li>
 *   <li>{@link semcomdt.swsecurity.ssrt.Relation#getTarget <em>Target</em>}</li>
 * </ul>
 *
 * @see semcomdt.swsecurity.ssrt.SsrtPackage#getRelation()
 * @model
 * @generated
 */
public interface Relation extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see semcomdt.swsecurity.ssrt.SsrtPackage#getRelation_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link semcomdt.swsecurity.ssrt.Relation#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' reference.
   * @see #setTarget(SolutionElement)
   * @see semcomdt.swsecurity.ssrt.SsrtPackage#getRelation_Target()
   * @model
   * @generated
   */
  SolutionElement getTarget();

  /**
   * Sets the value of the '{@link semcomdt.swsecurity.ssrt.Relation#getTarget <em>Target</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(SolutionElement value);

} // Relation
