/**
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity.ssrt;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>SST Level</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see semcomdt.swsecurity.ssrt.SsrtPackage#getSSTLevel()
 * @model
 * @generated
 */
public enum SSTLevel implements Enumerator
{
  /**
   * The '<em><b>Conceptual</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CONCEPTUAL_VALUE
   * @generated
   * @ordered
   */
  CONCEPTUAL(0, "Conceptual", "Conceptual"),

  /**
   * The '<em><b>Design</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DESIGN_VALUE
   * @generated
   * @ordered
   */
  DESIGN(1, "Design", "Design"),

  /**
   * The '<em><b>Realization</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #REALIZATION_VALUE
   * @generated
   * @ordered
   */
  REALIZATION(2, "Realization", "Realization");

  /**
   * The '<em><b>Conceptual</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CONCEPTUAL
   * @model name="Conceptual"
   * @generated
   * @ordered
   */
  public static final int CONCEPTUAL_VALUE = 0;

  /**
   * The '<em><b>Design</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DESIGN
   * @model name="Design"
   * @generated
   * @ordered
   */
  public static final int DESIGN_VALUE = 1;

  /**
   * The '<em><b>Realization</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #REALIZATION
   * @model name="Realization"
   * @generated
   * @ordered
   */
  public static final int REALIZATION_VALUE = 2;

  /**
   * An array of all the '<em><b>SST Level</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final SSTLevel[] VALUES_ARRAY =
    new SSTLevel[]
    {
      CONCEPTUAL,
      DESIGN,
      REALIZATION,
    };

  /**
   * A public read-only list of all the '<em><b>SST Level</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<SSTLevel> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>SST Level</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static SSTLevel get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      SSTLevel result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>SST Level</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static SSTLevel getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      SSTLevel result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>SST Level</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static SSTLevel get(int value)
  {
    switch (value)
    {
      case CONCEPTUAL_VALUE: return CONCEPTUAL;
      case DESIGN_VALUE: return DESIGN;
      case REALIZATION_VALUE: return REALIZATION;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private SSTLevel(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //SSTLevel
