/**
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity.ssrt.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import semcomdt.swsecurity.ssrt.Relation;
import semcomdt.swsecurity.ssrt.SolutionElement;
import semcomdt.swsecurity.ssrt.SsrtPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Relation</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link semcomdt.swsecurity.ssrt.impl.RelationImpl#getName <em>Name</em>}</li>
 *   <li>{@link semcomdt.swsecurity.ssrt.impl.RelationImpl#getRefines <em>Refines</em>}</li>
 *   <li>{@link semcomdt.swsecurity.ssrt.impl.RelationImpl#getDefinition <em>Definition</em>}</li>
 *   <li>{@link semcomdt.swsecurity.ssrt.impl.RelationImpl#getIn <em>In</em>}</li>
 *   <li>{@link semcomdt.swsecurity.ssrt.impl.RelationImpl#getOut <em>Out</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RelationImpl extends MinimalEObjectImpl.Container implements Relation
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getRefines() <em>Refines</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRefines()
   * @generated
   * @ordered
   */
  protected Relation refines;

  /**
   * The default value of the '{@link #getDefinition() <em>Definition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDefinition()
   * @generated
   * @ordered
   */
  protected static final String DEFINITION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDefinition() <em>Definition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDefinition()
   * @generated
   * @ordered
   */
  protected String definition = DEFINITION_EDEFAULT;

  /**
   * The cached value of the '{@link #getIn() <em>In</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIn()
   * @generated
   * @ordered
   */
  protected SolutionElement in;

  /**
   * The cached value of the '{@link #getOut() <em>Out</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOut()
   * @generated
   * @ordered
   */
  protected SolutionElement out;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RelationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SsrtPackage.Literals.RELATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SsrtPackage.RELATION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Relation getRefines()
  {
    if (refines != null && refines.eIsProxy())
    {
      InternalEObject oldRefines = (InternalEObject)refines;
      refines = (Relation)eResolveProxy(oldRefines);
      if (refines != oldRefines)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, SsrtPackage.RELATION__REFINES, oldRefines, refines));
      }
    }
    return refines;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Relation basicGetRefines()
  {
    return refines;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRefines(Relation newRefines)
  {
    Relation oldRefines = refines;
    refines = newRefines;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SsrtPackage.RELATION__REFINES, oldRefines, refines));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDefinition()
  {
    return definition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDefinition(String newDefinition)
  {
    String oldDefinition = definition;
    definition = newDefinition;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SsrtPackage.RELATION__DEFINITION, oldDefinition, definition));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SolutionElement getIn()
  {
    if (in != null && in.eIsProxy())
    {
      InternalEObject oldIn = (InternalEObject)in;
      in = (SolutionElement)eResolveProxy(oldIn);
      if (in != oldIn)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, SsrtPackage.RELATION__IN, oldIn, in));
      }
    }
    return in;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SolutionElement basicGetIn()
  {
    return in;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIn(SolutionElement newIn)
  {
    SolutionElement oldIn = in;
    in = newIn;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SsrtPackage.RELATION__IN, oldIn, in));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SolutionElement getOut()
  {
    if (out != null && out.eIsProxy())
    {
      InternalEObject oldOut = (InternalEObject)out;
      out = (SolutionElement)eResolveProxy(oldOut);
      if (out != oldOut)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, SsrtPackage.RELATION__OUT, oldOut, out));
      }
    }
    return out;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SolutionElement basicGetOut()
  {
    return out;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOut(SolutionElement newOut)
  {
    SolutionElement oldOut = out;
    out = newOut;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SsrtPackage.RELATION__OUT, oldOut, out));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SsrtPackage.RELATION__NAME:
        return getName();
      case SsrtPackage.RELATION__REFINES:
        if (resolve) return getRefines();
        return basicGetRefines();
      case SsrtPackage.RELATION__DEFINITION:
        return getDefinition();
      case SsrtPackage.RELATION__IN:
        if (resolve) return getIn();
        return basicGetIn();
      case SsrtPackage.RELATION__OUT:
        if (resolve) return getOut();
        return basicGetOut();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SsrtPackage.RELATION__NAME:
        setName((String)newValue);
        return;
      case SsrtPackage.RELATION__REFINES:
        setRefines((Relation)newValue);
        return;
      case SsrtPackage.RELATION__DEFINITION:
        setDefinition((String)newValue);
        return;
      case SsrtPackage.RELATION__IN:
        setIn((SolutionElement)newValue);
        return;
      case SsrtPackage.RELATION__OUT:
        setOut((SolutionElement)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SsrtPackage.RELATION__NAME:
        setName(NAME_EDEFAULT);
        return;
      case SsrtPackage.RELATION__REFINES:
        setRefines((Relation)null);
        return;
      case SsrtPackage.RELATION__DEFINITION:
        setDefinition(DEFINITION_EDEFAULT);
        return;
      case SsrtPackage.RELATION__IN:
        setIn((SolutionElement)null);
        return;
      case SsrtPackage.RELATION__OUT:
        setOut((SolutionElement)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SsrtPackage.RELATION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case SsrtPackage.RELATION__REFINES:
        return refines != null;
      case SsrtPackage.RELATION__DEFINITION:
        return DEFINITION_EDEFAULT == null ? definition != null : !DEFINITION_EDEFAULT.equals(definition);
      case SsrtPackage.RELATION__IN:
        return in != null;
      case SsrtPackage.RELATION__OUT:
        return out != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", definition: ");
    result.append(definition);
    result.append(')');
    return result.toString();
  }

} //RelationImpl
