/*
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity.objective.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.eclipse.xtext.web.server.persistence.IResourceBaseProvider;

import semcomdt.swsecurity.objective.CiaampsRuntimeModule;
import semcomdt.swsecurity.objective.CiaampsStandaloneSetup;
import semcomdt.swsecurity.objective.ide.CiaampsIdeModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class CiaampsWebSetup extends CiaampsStandaloneSetup {
	private final IResourceBaseProvider resourceBaseProvider;

	public CiaampsWebSetup(IResourceBaseProvider resourceBaseProvider) {
		this.resourceBaseProvider = resourceBaseProvider;
	}
	
	@Override
	public Injector createInjector() {
		CiaampsWebModule webmodule = new CiaampsWebModule(this.resourceBaseProvider);
		return Guice.createInjector(Modules2.mixin(new CiaampsRuntimeModule(), new CiaampsIdeModule(), webmodule));
	}
	
}
