/*
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity.objective.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class CiaampsWebModule extends AbstractCiaampsWebModule {
}
