/**
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity.ssrt.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.EObjectResolvingEList;
import org.eclipse.emf.ecore.util.InternalEList;

import semcomdt.swsecurity.objective.ciaamps.SecurityProperty;

import semcomdt.swsecurity.ssrt.Solution;
import semcomdt.swsecurity.ssrt.SolutionTree;
import semcomdt.swsecurity.ssrt.SsrtPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Solution Tree</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link semcomdt.swsecurity.ssrt.impl.SolutionTreeImpl#getName <em>Name</em>}</li>
 *   <li>{@link semcomdt.swsecurity.ssrt.impl.SolutionTreeImpl#getContributesTo <em>Contributes To</em>}</li>
 *   <li>{@link semcomdt.swsecurity.ssrt.impl.SolutionTreeImpl#getProvides <em>Provides</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SolutionTreeImpl extends MinimalEObjectImpl.Container implements SolutionTree
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getContributesTo() <em>Contributes To</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getContributesTo()
   * @generated
   * @ordered
   */
  protected EList<SecurityProperty> contributesTo;

  /**
   * The cached value of the '{@link #getProvides() <em>Provides</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProvides()
   * @generated
   * @ordered
   */
  protected EList<Solution> provides;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SolutionTreeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SsrtPackage.Literals.SOLUTION_TREE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SsrtPackage.SOLUTION_TREE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<SecurityProperty> getContributesTo()
  {
    if (contributesTo == null)
    {
      contributesTo = new EObjectResolvingEList<SecurityProperty>(SecurityProperty.class, this, SsrtPackage.SOLUTION_TREE__CONTRIBUTES_TO);
    }
    return contributesTo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Solution> getProvides()
  {
    if (provides == null)
    {
      provides = new EObjectContainmentEList<Solution>(Solution.class, this, SsrtPackage.SOLUTION_TREE__PROVIDES);
    }
    return provides;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SsrtPackage.SOLUTION_TREE__PROVIDES:
        return ((InternalEList<?>)getProvides()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SsrtPackage.SOLUTION_TREE__NAME:
        return getName();
      case SsrtPackage.SOLUTION_TREE__CONTRIBUTES_TO:
        return getContributesTo();
      case SsrtPackage.SOLUTION_TREE__PROVIDES:
        return getProvides();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SsrtPackage.SOLUTION_TREE__NAME:
        setName((String)newValue);
        return;
      case SsrtPackage.SOLUTION_TREE__CONTRIBUTES_TO:
        getContributesTo().clear();
        getContributesTo().addAll((Collection<? extends SecurityProperty>)newValue);
        return;
      case SsrtPackage.SOLUTION_TREE__PROVIDES:
        getProvides().clear();
        getProvides().addAll((Collection<? extends Solution>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SsrtPackage.SOLUTION_TREE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case SsrtPackage.SOLUTION_TREE__CONTRIBUTES_TO:
        getContributesTo().clear();
        return;
      case SsrtPackage.SOLUTION_TREE__PROVIDES:
        getProvides().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SsrtPackage.SOLUTION_TREE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case SsrtPackage.SOLUTION_TREE__CONTRIBUTES_TO:
        return contributesTo != null && !contributesTo.isEmpty();
      case SsrtPackage.SOLUTION_TREE__PROVIDES:
        return provides != null && !provides.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //SolutionTreeImpl
