/*
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import semcomdt.swsecurity.ssrt.xtext.ui.internal.XtextActivator;

public class SsrtUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("semcomdt.swsecurity.Ssrt");
	}

}
