/**
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity.ssrt;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Solution</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link semcomdt.swsecurity.ssrt.Solution#getKind <em>Kind</em>}</li>
 *   <li>{@link semcomdt.swsecurity.ssrt.Solution#getLevel <em>Level</em>}</li>
 *   <li>{@link semcomdt.swsecurity.ssrt.Solution#getName <em>Name</em>}</li>
 *   <li>{@link semcomdt.swsecurity.ssrt.Solution#getRefines <em>Refines</em>}</li>
 *   <li>{@link semcomdt.swsecurity.ssrt.Solution#getSolutionelements <em>Solutionelements</em>}</li>
 * </ul>
 *
 * @see semcomdt.swsecurity.ssrt.SsrtPackage#getSolution()
 * @model
 * @generated
 */
public interface Solution extends EObject
{
  /**
   * Returns the value of the '<em><b>Kind</b></em>' attribute.
   * The literals are from the enumeration {@link semcomdt.swsecurity.ssrt.SolutionType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Kind</em>' attribute.
   * @see semcomdt.swsecurity.ssrt.SolutionType
   * @see #setKind(SolutionType)
   * @see semcomdt.swsecurity.ssrt.SsrtPackage#getSolution_Kind()
   * @model
   * @generated
   */
  SolutionType getKind();

  /**
   * Sets the value of the '{@link semcomdt.swsecurity.ssrt.Solution#getKind <em>Kind</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Kind</em>' attribute.
   * @see semcomdt.swsecurity.ssrt.SolutionType
   * @see #getKind()
   * @generated
   */
  void setKind(SolutionType value);

  /**
   * Returns the value of the '<em><b>Level</b></em>' attribute.
   * The literals are from the enumeration {@link semcomdt.swsecurity.ssrt.Level}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Level</em>' attribute.
   * @see semcomdt.swsecurity.ssrt.Level
   * @see #setLevel(Level)
   * @see semcomdt.swsecurity.ssrt.SsrtPackage#getSolution_Level()
   * @model
   * @generated
   */
  Level getLevel();

  /**
   * Sets the value of the '{@link semcomdt.swsecurity.ssrt.Solution#getLevel <em>Level</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Level</em>' attribute.
   * @see semcomdt.swsecurity.ssrt.Level
   * @see #getLevel()
   * @generated
   */
  void setLevel(Level value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see semcomdt.swsecurity.ssrt.SsrtPackage#getSolution_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link semcomdt.swsecurity.ssrt.Solution#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Refines</b></em>' reference list.
   * The list contents are of type {@link semcomdt.swsecurity.ssrt.Solution}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Refines</em>' reference list.
   * @see semcomdt.swsecurity.ssrt.SsrtPackage#getSolution_Refines()
   * @model
   * @generated
   */
  EList<Solution> getRefines();

  /**
   * Returns the value of the '<em><b>Solutionelements</b></em>' containment reference list.
   * The list contents are of type {@link semcomdt.swsecurity.ssrt.Element}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Solutionelements</em>' containment reference list.
   * @see semcomdt.swsecurity.ssrt.SsrtPackage#getSolution_Solutionelements()
   * @model containment="true"
   * @generated
   */
  EList<Element> getSolutionelements();

} // Solution
