/**
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity.objective.ciaamps.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import semcomdt.swsecurity.objective.ciaamps.AssetDetails;
import semcomdt.swsecurity.objective.ciaamps.Assets;
import semcomdt.swsecurity.objective.ciaamps.CiaampsPackage;
import semcomdt.swsecurity.objective.ciaamps.Import;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Assets</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link semcomdt.swsecurity.objective.ciaamps.impl.AssetsImpl#getImports <em>Imports</em>}</li>
 *   <li>{@link semcomdt.swsecurity.objective.ciaamps.impl.AssetsImpl#getAssets <em>Assets</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AssetsImpl extends MinimalEObjectImpl.Container implements Assets
{
  /**
   * The cached value of the '{@link #getImports() <em>Imports</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImports()
   * @generated
   * @ordered
   */
  protected EList<Import> imports;

  /**
   * The cached value of the '{@link #getAssets() <em>Assets</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAssets()
   * @generated
   * @ordered
   */
  protected EList<AssetDetails> assets;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AssetsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CiaampsPackage.Literals.ASSETS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Import> getImports()
  {
    if (imports == null)
    {
      imports = new EObjectContainmentEList<Import>(Import.class, this, CiaampsPackage.ASSETS__IMPORTS);
    }
    return imports;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<AssetDetails> getAssets()
  {
    if (assets == null)
    {
      assets = new EObjectContainmentEList<AssetDetails>(AssetDetails.class, this, CiaampsPackage.ASSETS__ASSETS);
    }
    return assets;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case CiaampsPackage.ASSETS__IMPORTS:
        return ((InternalEList<?>)getImports()).basicRemove(otherEnd, msgs);
      case CiaampsPackage.ASSETS__ASSETS:
        return ((InternalEList<?>)getAssets()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CiaampsPackage.ASSETS__IMPORTS:
        return getImports();
      case CiaampsPackage.ASSETS__ASSETS:
        return getAssets();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CiaampsPackage.ASSETS__IMPORTS:
        getImports().clear();
        getImports().addAll((Collection<? extends Import>)newValue);
        return;
      case CiaampsPackage.ASSETS__ASSETS:
        getAssets().clear();
        getAssets().addAll((Collection<? extends AssetDetails>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CiaampsPackage.ASSETS__IMPORTS:
        getImports().clear();
        return;
      case CiaampsPackage.ASSETS__ASSETS:
        getAssets().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CiaampsPackage.ASSETS__IMPORTS:
        return imports != null && !imports.isEmpty();
      case CiaampsPackage.ASSETS__ASSETS:
        return assets != null && !assets.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //AssetsImpl
