/**
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity.objective.ciaamps.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import semcomdt.swarchitecture.cbse.Element;

import semcomdt.swsecurity.objective.ciaamps.Asset;
import semcomdt.swsecurity.objective.ciaamps.CiaampsPackage;
import semcomdt.swsecurity.objective.ciaamps.SecurityProperty;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Asset</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link semcomdt.swsecurity.objective.ciaamps.impl.AssetImpl#getEnsureSP <em>Ensure SP</em>}</li>
 *   <li>{@link semcomdt.swsecurity.objective.ciaamps.impl.AssetImpl#getRefersToAE <em>Refers To AE</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AssetImpl extends AssetDetailsImpl implements Asset
{
  /**
   * The cached value of the '{@link #getEnsureSP() <em>Ensure SP</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnsureSP()
   * @generated
   * @ordered
   */
  protected SecurityProperty ensureSP;

  /**
   * The cached value of the '{@link #getRefersToAE() <em>Refers To AE</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRefersToAE()
   * @generated
   * @ordered
   */
  protected Element refersToAE;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AssetImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CiaampsPackage.Literals.ASSET;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SecurityProperty getEnsureSP()
  {
    if (ensureSP != null && ensureSP.eIsProxy())
    {
      InternalEObject oldEnsureSP = (InternalEObject)ensureSP;
      ensureSP = (SecurityProperty)eResolveProxy(oldEnsureSP);
      if (ensureSP != oldEnsureSP)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, CiaampsPackage.ASSET__ENSURE_SP, oldEnsureSP, ensureSP));
      }
    }
    return ensureSP;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SecurityProperty basicGetEnsureSP()
  {
    return ensureSP;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEnsureSP(SecurityProperty newEnsureSP)
  {
    SecurityProperty oldEnsureSP = ensureSP;
    ensureSP = newEnsureSP;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CiaampsPackage.ASSET__ENSURE_SP, oldEnsureSP, ensureSP));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Element getRefersToAE()
  {
    if (refersToAE != null && refersToAE.eIsProxy())
    {
      InternalEObject oldRefersToAE = (InternalEObject)refersToAE;
      refersToAE = (Element)eResolveProxy(oldRefersToAE);
      if (refersToAE != oldRefersToAE)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, CiaampsPackage.ASSET__REFERS_TO_AE, oldRefersToAE, refersToAE));
      }
    }
    return refersToAE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Element basicGetRefersToAE()
  {
    return refersToAE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRefersToAE(Element newRefersToAE)
  {
    Element oldRefersToAE = refersToAE;
    refersToAE = newRefersToAE;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CiaampsPackage.ASSET__REFERS_TO_AE, oldRefersToAE, refersToAE));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CiaampsPackage.ASSET__ENSURE_SP:
        if (resolve) return getEnsureSP();
        return basicGetEnsureSP();
      case CiaampsPackage.ASSET__REFERS_TO_AE:
        if (resolve) return getRefersToAE();
        return basicGetRefersToAE();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CiaampsPackage.ASSET__ENSURE_SP:
        setEnsureSP((SecurityProperty)newValue);
        return;
      case CiaampsPackage.ASSET__REFERS_TO_AE:
        setRefersToAE((Element)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CiaampsPackage.ASSET__ENSURE_SP:
        setEnsureSP((SecurityProperty)null);
        return;
      case CiaampsPackage.ASSET__REFERS_TO_AE:
        setRefersToAE((Element)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CiaampsPackage.ASSET__ENSURE_SP:
        return ensureSP != null;
      case CiaampsPackage.ASSET__REFERS_TO_AE:
        return refersToAE != null;
    }
    return super.eIsSet(featureID);
  }

} //AssetImpl
