/*
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity.objective.ciaamps.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractCiaampsValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(semcomdt.swsecurity.objective.ciaamps.ciaamps.CiaampsPackage.eINSTANCE);
		return result;
	}
}
