/*
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SsrtAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("semcomdt/swsecurity/parser/antlr/internal/InternalSsrt.tokens");
	}
}
