/*
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity.objective.ciaamps.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import semcomdt.swsecurity.objective.ciaamps.ciaamps.Asset;
import semcomdt.swsecurity.objective.ciaamps.ciaamps.Assets;
import semcomdt.swsecurity.objective.ciaamps.ciaamps.CiaampsPackage;
import semcomdt.swsecurity.objective.ciaamps.ciaamps.Import;
import semcomdt.swsecurity.objective.ciaamps.ciaamps.PropertyCategory;
import semcomdt.swsecurity.objective.ciaamps.ciaamps.SecurityProperty;
import semcomdt.swsecurity.objective.ciaamps.services.CiaampsGrammarAccess;

@SuppressWarnings("all")
public class CiaampsSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private CiaampsGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == CiaampsPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case CiaampsPackage.ASSET:
				sequence_Asset(context, (Asset) semanticObject); 
				return; 
			case CiaampsPackage.ASSETS:
				sequence_Assets(context, (Assets) semanticObject); 
				return; 
			case CiaampsPackage.IMPORT:
				sequence_Import(context, (Import) semanticObject); 
				return; 
			case CiaampsPackage.PROPERTY_CATEGORY:
				sequence_PropertyCategory(context, (PropertyCategory) semanticObject); 
				return; 
			case CiaampsPackage.SECURITY_PROPERTY:
				sequence_SecurityProperty(context, (SecurityProperty) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     AssetDetails returns Asset
	 *     Asset returns Asset
	 *
	 * Constraint:
	 *     (name=ID ensureSP=[SecurityProperty|QualifiedName] refersToAE=[Element|QualifiedName]?)
	 * </pre>
	 */
	protected void sequence_Asset(ISerializationContext context, Asset semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Assets returns Assets
	 *
	 * Constraint:
	 *     ((imports+=Import+ assets+=AssetDetails+) | assets+=AssetDetails+)?
	 * </pre>
	 */
	protected void sequence_Assets(ISerializationContext context, Assets semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Import returns Import
	 *
	 * Constraint:
	 *     importURI=STRING
	 * </pre>
	 */
	protected void sequence_Import(ISerializationContext context, Import semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, CiaampsPackage.Literals.IMPORT__IMPORT_URI) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CiaampsPackage.Literals.IMPORT__IMPORT_URI));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getImportAccess().getImportURISTRINGTerminalRuleCall_1_0(), semanticObject.getImportURI());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AssetDetails returns PropertyCategory
	 *     PropertyCategory returns PropertyCategory
	 *
	 * Constraint:
	 *     (name=ID secprop+=SecurityProperty*)
	 * </pre>
	 */
	protected void sequence_PropertyCategory(ISerializationContext context, PropertyCategory semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AssetDetails returns SecurityProperty
	 *     SecurityProperty returns SecurityProperty
	 *
	 * Constraint:
	 *     name=ID
	 * </pre>
	 */
	protected void sequence_SecurityProperty(ISerializationContext context, SecurityProperty semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, CiaampsPackage.Literals.ASSET_DETAILS__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CiaampsPackage.Literals.ASSET_DETAILS__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSecurityPropertyAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
}
