/*
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity.objective.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link CiaampsWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractCiaampsWebModule extends DefaultWebModule {

}
