/**
 * generated by Xtext 2.35.0
 */
package semcomdt.swarchitecture.cbse;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Architecture Element Type</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see semcomdt.swarchitecture.cbse.CbsePackage#getArchitectureElementType()
 * @model
 * @generated
 */
public enum ArchitectureElementType implements Enumerator
{
  /**
   * The '<em><b>Component</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #COMPONENT_VALUE
   * @generated
   * @ordered
   */
  COMPONENT(0, "component", "Component"),

  /**
   * The '<em><b>Connector</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CONNECTOR_VALUE
   * @generated
   * @ordered
   */
  CONNECTOR(1, "connector", "Connector"),

  /**
   * The '<em><b>Activecomponent</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ACTIVECOMPONENT_VALUE
   * @generated
   * @ordered
   */
  ACTIVECOMPONENT(2, "activecomponent", "ActiveComponent"),

  /**
   * The '<em><b>Passivecomponent</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PASSIVECOMPONENT_VALUE
   * @generated
   * @ordered
   */
  PASSIVECOMPONENT(3, "passivecomponent", "PassiveComponent");

  /**
   * The '<em><b>Component</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #COMPONENT
   * @model name="component" literal="Component"
   * @generated
   * @ordered
   */
  public static final int COMPONENT_VALUE = 0;

  /**
   * The '<em><b>Connector</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CONNECTOR
   * @model name="connector" literal="Connector"
   * @generated
   * @ordered
   */
  public static final int CONNECTOR_VALUE = 1;

  /**
   * The '<em><b>Activecomponent</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ACTIVECOMPONENT
   * @model name="activecomponent" literal="ActiveComponent"
   * @generated
   * @ordered
   */
  public static final int ACTIVECOMPONENT_VALUE = 2;

  /**
   * The '<em><b>Passivecomponent</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PASSIVECOMPONENT
   * @model name="passivecomponent" literal="PassiveComponent"
   * @generated
   * @ordered
   */
  public static final int PASSIVECOMPONENT_VALUE = 3;

  /**
   * An array of all the '<em><b>Architecture Element Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final ArchitectureElementType[] VALUES_ARRAY =
    new ArchitectureElementType[]
    {
      COMPONENT,
      CONNECTOR,
      ACTIVECOMPONENT,
      PASSIVECOMPONENT,
    };

  /**
   * A public read-only list of all the '<em><b>Architecture Element Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<ArchitectureElementType> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Architecture Element Type</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ArchitectureElementType get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      ArchitectureElementType result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Architecture Element Type</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ArchitectureElementType getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      ArchitectureElementType result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Architecture Element Type</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ArchitectureElementType get(int value)
  {
    switch (value)
    {
      case COMPONENT_VALUE: return COMPONENT;
      case CONNECTOR_VALUE: return CONNECTOR;
      case ACTIVECOMPONENT_VALUE: return ACTIVECOMPONENT;
      case PASSIVECOMPONENT_VALUE: return PASSIVECOMPONENT;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private ArchitectureElementType(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //ArchitectureElementType
