/**
 * generated by Xtext 2.35.0
 */
package semcomdt.swarchitecture.cbse;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cbse</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link semcomdt.swarchitecture.cbse.Cbse#getSystem <em>System</em>}</li>
 * </ul>
 *
 * @see semcomdt.swarchitecture.cbse.CbsePackage#getCbse()
 * @model
 * @generated
 */
public interface Cbse extends EObject
{
  /**
   * Returns the value of the '<em><b>System</b></em>' containment reference list.
   * The list contents are of type {@link semcomdt.swarchitecture.cbse.Element}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>System</em>' containment reference list.
   * @see semcomdt.swarchitecture.cbse.CbsePackage#getCbse_System()
   * @model containment="true"
   * @generated
   */
  EList<Element> getSystem();

} // Cbse
