/**
 * generated by Xtext 2.35.0
 */
package semcomdt.swarchitecture.cbse;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see semcomdt.swarchitecture.cbse.CbseFactory
 * @model kind="package"
 * @generated
 */
public interface CbsePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "cbse";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.semcomdt.swarchitecture/Cbse";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "cbse";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CbsePackage eINSTANCE = semcomdt.swarchitecture.cbse.impl.CbsePackageImpl.init();

  /**
   * The meta object id for the '{@link semcomdt.swarchitecture.cbse.impl.CbseImpl <em>Cbse</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see semcomdt.swarchitecture.cbse.impl.CbseImpl
   * @see semcomdt.swarchitecture.cbse.impl.CbsePackageImpl#getCbse()
   * @generated
   */
  int CBSE = 0;

  /**
   * The feature id for the '<em><b>System</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CBSE__SYSTEM = 0;

  /**
   * The number of structural features of the '<em>Cbse</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CBSE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link semcomdt.swarchitecture.cbse.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see semcomdt.swarchitecture.cbse.impl.ElementImpl
   * @see semcomdt.swarchitecture.cbse.impl.CbsePackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link semcomdt.swarchitecture.cbse.impl.ComponentImpl <em>Component</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see semcomdt.swarchitecture.cbse.impl.ComponentImpl
   * @see semcomdt.swarchitecture.cbse.impl.CbsePackageImpl#getComponent()
   * @generated
   */
  int COMPONENT = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__NAME = ELEMENT__NAME;

  /**
   * The number of structural features of the '<em>Component</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link semcomdt.swarchitecture.cbse.impl.ConnectorImpl <em>Connector</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see semcomdt.swarchitecture.cbse.impl.ConnectorImpl
   * @see semcomdt.swarchitecture.cbse.impl.CbsePackageImpl#getConnector()
   * @generated
   */
  int CONNECTOR = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTOR__NAME = ELEMENT__NAME;

  /**
   * The number of structural features of the '<em>Connector</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTOR_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link semcomdt.swarchitecture.cbse.impl.PortImpl <em>Port</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see semcomdt.swarchitecture.cbse.impl.PortImpl
   * @see semcomdt.swarchitecture.cbse.impl.CbsePackageImpl#getPort()
   * @generated
   */
  int PORT = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORT__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Kind</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORT__KIND = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Interaction Nature</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORT__INTERACTION_NATURE = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Port</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORT_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link semcomdt.swarchitecture.cbse.impl.PassiveComponentImpl <em>Passive Component</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see semcomdt.swarchitecture.cbse.impl.PassiveComponentImpl
   * @see semcomdt.swarchitecture.cbse.impl.CbsePackageImpl#getPassiveComponent()
   * @generated
   */
  int PASSIVE_COMPONENT = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PASSIVE_COMPONENT__NAME = COMPONENT__NAME;

  /**
   * The number of structural features of the '<em>Passive Component</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PASSIVE_COMPONENT_FEATURE_COUNT = COMPONENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link semcomdt.swarchitecture.cbse.impl.ActiveComponentImpl <em>Active Component</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see semcomdt.swarchitecture.cbse.impl.ActiveComponentImpl
   * @see semcomdt.swarchitecture.cbse.impl.CbsePackageImpl#getActiveComponent()
   * @generated
   */
  int ACTIVE_COMPONENT = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTIVE_COMPONENT__NAME = COMPONENT__NAME;

  /**
   * The feature id for the '<em><b>Functions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTIVE_COMPONENT__FUNCTIONS = COMPONENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Active Component</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTIVE_COMPONENT_FEATURE_COUNT = COMPONENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link semcomdt.swarchitecture.cbse.impl.FunctionImpl <em>Function</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see semcomdt.swarchitecture.cbse.impl.FunctionImpl
   * @see semcomdt.swarchitecture.cbse.impl.CbsePackageImpl#getFunction()
   * @generated
   */
  int FUNCTION = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__NAME = 0;

  /**
   * The number of structural features of the '<em>Function</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link semcomdt.swarchitecture.cbse.impl.InteractionNatureImpl <em>Interaction Nature</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see semcomdt.swarchitecture.cbse.impl.InteractionNatureImpl
   * @see semcomdt.swarchitecture.cbse.impl.CbsePackageImpl#getInteractionNature()
   * @generated
   */
  int INTERACTION_NATURE = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERACTION_NATURE__NAME = 0;

  /**
   * The number of structural features of the '<em>Interaction Nature</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERACTION_NATURE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link semcomdt.swarchitecture.cbse.impl.DataImpl <em>Data</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see semcomdt.swarchitecture.cbse.impl.DataImpl
   * @see semcomdt.swarchitecture.cbse.impl.CbsePackageImpl#getData()
   * @generated
   */
  int DATA = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA__NAME = 0;

  /**
   * The feature id for the '<em><b>Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA__SUPER_TYPE = 1;

  /**
   * The number of structural features of the '<em>Data</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link semcomdt.swarchitecture.cbse.impl.DataTypeImpl <em>Data Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see semcomdt.swarchitecture.cbse.impl.DataTypeImpl
   * @see semcomdt.swarchitecture.cbse.impl.CbsePackageImpl#getDataType()
   * @generated
   */
  int DATA_TYPE = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_TYPE__NAME = 0;

  /**
   * The number of structural features of the '<em>Data Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link semcomdt.swarchitecture.cbse.impl.PayloadImpl <em>Payload</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see semcomdt.swarchitecture.cbse.impl.PayloadImpl
   * @see semcomdt.swarchitecture.cbse.impl.CbsePackageImpl#getPayload()
   * @generated
   */
  int PAYLOAD = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAYLOAD__NAME = 0;

  /**
   * The number of structural features of the '<em>Payload</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAYLOAD_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link semcomdt.swarchitecture.cbse.impl.MsgExchangeImpl <em>Msg Exchange</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see semcomdt.swarchitecture.cbse.impl.MsgExchangeImpl
   * @see semcomdt.swarchitecture.cbse.impl.CbsePackageImpl#getMsgExchange()
   * @generated
   */
  int MSG_EXCHANGE = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MSG_EXCHANGE__NAME = 0;

  /**
   * The number of structural features of the '<em>Msg Exchange</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MSG_EXCHANGE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link semcomdt.swarchitecture.cbse.impl.CommunicationStyleImpl <em>Communication Style</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see semcomdt.swarchitecture.cbse.impl.CommunicationStyleImpl
   * @see semcomdt.swarchitecture.cbse.impl.CbsePackageImpl#getCommunicationStyle()
   * @generated
   */
  int COMMUNICATION_STYLE = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMUNICATION_STYLE__NAME = 0;

  /**
   * The number of structural features of the '<em>Communication Style</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMUNICATION_STYLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link semcomdt.swarchitecture.cbse.PortKind <em>Port Kind</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see semcomdt.swarchitecture.cbse.PortKind
   * @see semcomdt.swarchitecture.cbse.impl.CbsePackageImpl#getPortKind()
   * @generated
   */
  int PORT_KIND = 14;

  /**
   * The meta object id for the '{@link semcomdt.swarchitecture.cbse.ArchitectureElementType <em>Architecture Element Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see semcomdt.swarchitecture.cbse.ArchitectureElementType
   * @see semcomdt.swarchitecture.cbse.impl.CbsePackageImpl#getArchitectureElementType()
   * @generated
   */
  int ARCHITECTURE_ELEMENT_TYPE = 15;


  /**
   * Returns the meta object for class '{@link semcomdt.swarchitecture.cbse.Cbse <em>Cbse</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cbse</em>'.
   * @see semcomdt.swarchitecture.cbse.Cbse
   * @generated
   */
  EClass getCbse();

  /**
   * Returns the meta object for the containment reference list '{@link semcomdt.swarchitecture.cbse.Cbse#getSystem <em>System</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>System</em>'.
   * @see semcomdt.swarchitecture.cbse.Cbse#getSystem()
   * @see #getCbse()
   * @generated
   */
  EReference getCbse_System();

  /**
   * Returns the meta object for class '{@link semcomdt.swarchitecture.cbse.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see semcomdt.swarchitecture.cbse.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for the attribute '{@link semcomdt.swarchitecture.cbse.Element#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see semcomdt.swarchitecture.cbse.Element#getName()
   * @see #getElement()
   * @generated
   */
  EAttribute getElement_Name();

  /**
   * Returns the meta object for class '{@link semcomdt.swarchitecture.cbse.Component <em>Component</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Component</em>'.
   * @see semcomdt.swarchitecture.cbse.Component
   * @generated
   */
  EClass getComponent();

  /**
   * Returns the meta object for class '{@link semcomdt.swarchitecture.cbse.Connector <em>Connector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Connector</em>'.
   * @see semcomdt.swarchitecture.cbse.Connector
   * @generated
   */
  EClass getConnector();

  /**
   * Returns the meta object for class '{@link semcomdt.swarchitecture.cbse.Port <em>Port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Port</em>'.
   * @see semcomdt.swarchitecture.cbse.Port
   * @generated
   */
  EClass getPort();

  /**
   * Returns the meta object for the attribute '{@link semcomdt.swarchitecture.cbse.Port#getKind <em>Kind</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Kind</em>'.
   * @see semcomdt.swarchitecture.cbse.Port#getKind()
   * @see #getPort()
   * @generated
   */
  EAttribute getPort_Kind();

  /**
   * Returns the meta object for the containment reference '{@link semcomdt.swarchitecture.cbse.Port#getInteractionNature <em>Interaction Nature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Interaction Nature</em>'.
   * @see semcomdt.swarchitecture.cbse.Port#getInteractionNature()
   * @see #getPort()
   * @generated
   */
  EReference getPort_InteractionNature();

  /**
   * Returns the meta object for class '{@link semcomdt.swarchitecture.cbse.PassiveComponent <em>Passive Component</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Passive Component</em>'.
   * @see semcomdt.swarchitecture.cbse.PassiveComponent
   * @generated
   */
  EClass getPassiveComponent();

  /**
   * Returns the meta object for class '{@link semcomdt.swarchitecture.cbse.ActiveComponent <em>Active Component</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Active Component</em>'.
   * @see semcomdt.swarchitecture.cbse.ActiveComponent
   * @generated
   */
  EClass getActiveComponent();

  /**
   * Returns the meta object for the containment reference list '{@link semcomdt.swarchitecture.cbse.ActiveComponent#getFunctions <em>Functions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Functions</em>'.
   * @see semcomdt.swarchitecture.cbse.ActiveComponent#getFunctions()
   * @see #getActiveComponent()
   * @generated
   */
  EReference getActiveComponent_Functions();

  /**
   * Returns the meta object for class '{@link semcomdt.swarchitecture.cbse.Function <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function</em>'.
   * @see semcomdt.swarchitecture.cbse.Function
   * @generated
   */
  EClass getFunction();

  /**
   * Returns the meta object for the attribute '{@link semcomdt.swarchitecture.cbse.Function#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see semcomdt.swarchitecture.cbse.Function#getName()
   * @see #getFunction()
   * @generated
   */
  EAttribute getFunction_Name();

  /**
   * Returns the meta object for class '{@link semcomdt.swarchitecture.cbse.InteractionNature <em>Interaction Nature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Interaction Nature</em>'.
   * @see semcomdt.swarchitecture.cbse.InteractionNature
   * @generated
   */
  EClass getInteractionNature();

  /**
   * Returns the meta object for the attribute '{@link semcomdt.swarchitecture.cbse.InteractionNature#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see semcomdt.swarchitecture.cbse.InteractionNature#getName()
   * @see #getInteractionNature()
   * @generated
   */
  EAttribute getInteractionNature_Name();

  /**
   * Returns the meta object for class '{@link semcomdt.swarchitecture.cbse.Data <em>Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Data</em>'.
   * @see semcomdt.swarchitecture.cbse.Data
   * @generated
   */
  EClass getData();

  /**
   * Returns the meta object for the attribute '{@link semcomdt.swarchitecture.cbse.Data#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see semcomdt.swarchitecture.cbse.Data#getName()
   * @see #getData()
   * @generated
   */
  EAttribute getData_Name();

  /**
   * Returns the meta object for the reference '{@link semcomdt.swarchitecture.cbse.Data#getSuperType <em>Super Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Super Type</em>'.
   * @see semcomdt.swarchitecture.cbse.Data#getSuperType()
   * @see #getData()
   * @generated
   */
  EReference getData_SuperType();

  /**
   * Returns the meta object for class '{@link semcomdt.swarchitecture.cbse.DataType <em>Data Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Data Type</em>'.
   * @see semcomdt.swarchitecture.cbse.DataType
   * @generated
   */
  EClass getDataType();

  /**
   * Returns the meta object for the attribute '{@link semcomdt.swarchitecture.cbse.DataType#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see semcomdt.swarchitecture.cbse.DataType#getName()
   * @see #getDataType()
   * @generated
   */
  EAttribute getDataType_Name();

  /**
   * Returns the meta object for class '{@link semcomdt.swarchitecture.cbse.Payload <em>Payload</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Payload</em>'.
   * @see semcomdt.swarchitecture.cbse.Payload
   * @generated
   */
  EClass getPayload();

  /**
   * Returns the meta object for the attribute '{@link semcomdt.swarchitecture.cbse.Payload#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see semcomdt.swarchitecture.cbse.Payload#getName()
   * @see #getPayload()
   * @generated
   */
  EAttribute getPayload_Name();

  /**
   * Returns the meta object for class '{@link semcomdt.swarchitecture.cbse.MsgExchange <em>Msg Exchange</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Msg Exchange</em>'.
   * @see semcomdt.swarchitecture.cbse.MsgExchange
   * @generated
   */
  EClass getMsgExchange();

  /**
   * Returns the meta object for the attribute '{@link semcomdt.swarchitecture.cbse.MsgExchange#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see semcomdt.swarchitecture.cbse.MsgExchange#getName()
   * @see #getMsgExchange()
   * @generated
   */
  EAttribute getMsgExchange_Name();

  /**
   * Returns the meta object for class '{@link semcomdt.swarchitecture.cbse.CommunicationStyle <em>Communication Style</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Communication Style</em>'.
   * @see semcomdt.swarchitecture.cbse.CommunicationStyle
   * @generated
   */
  EClass getCommunicationStyle();

  /**
   * Returns the meta object for the attribute '{@link semcomdt.swarchitecture.cbse.CommunicationStyle#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see semcomdt.swarchitecture.cbse.CommunicationStyle#getName()
   * @see #getCommunicationStyle()
   * @generated
   */
  EAttribute getCommunicationStyle_Name();

  /**
   * Returns the meta object for enum '{@link semcomdt.swarchitecture.cbse.PortKind <em>Port Kind</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Port Kind</em>'.
   * @see semcomdt.swarchitecture.cbse.PortKind
   * @generated
   */
  EEnum getPortKind();

  /**
   * Returns the meta object for enum '{@link semcomdt.swarchitecture.cbse.ArchitectureElementType <em>Architecture Element Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Architecture Element Type</em>'.
   * @see semcomdt.swarchitecture.cbse.ArchitectureElementType
   * @generated
   */
  EEnum getArchitectureElementType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  CbseFactory getCbseFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link semcomdt.swarchitecture.cbse.impl.CbseImpl <em>Cbse</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see semcomdt.swarchitecture.cbse.impl.CbseImpl
     * @see semcomdt.swarchitecture.cbse.impl.CbsePackageImpl#getCbse()
     * @generated
     */
    EClass CBSE = eINSTANCE.getCbse();

    /**
     * The meta object literal for the '<em><b>System</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CBSE__SYSTEM = eINSTANCE.getCbse_System();

    /**
     * The meta object literal for the '{@link semcomdt.swarchitecture.cbse.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see semcomdt.swarchitecture.cbse.impl.ElementImpl
     * @see semcomdt.swarchitecture.cbse.impl.CbsePackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT__NAME = eINSTANCE.getElement_Name();

    /**
     * The meta object literal for the '{@link semcomdt.swarchitecture.cbse.impl.ComponentImpl <em>Component</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see semcomdt.swarchitecture.cbse.impl.ComponentImpl
     * @see semcomdt.swarchitecture.cbse.impl.CbsePackageImpl#getComponent()
     * @generated
     */
    EClass COMPONENT = eINSTANCE.getComponent();

    /**
     * The meta object literal for the '{@link semcomdt.swarchitecture.cbse.impl.ConnectorImpl <em>Connector</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see semcomdt.swarchitecture.cbse.impl.ConnectorImpl
     * @see semcomdt.swarchitecture.cbse.impl.CbsePackageImpl#getConnector()
     * @generated
     */
    EClass CONNECTOR = eINSTANCE.getConnector();

    /**
     * The meta object literal for the '{@link semcomdt.swarchitecture.cbse.impl.PortImpl <em>Port</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see semcomdt.swarchitecture.cbse.impl.PortImpl
     * @see semcomdt.swarchitecture.cbse.impl.CbsePackageImpl#getPort()
     * @generated
     */
    EClass PORT = eINSTANCE.getPort();

    /**
     * The meta object literal for the '<em><b>Kind</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PORT__KIND = eINSTANCE.getPort_Kind();

    /**
     * The meta object literal for the '<em><b>Interaction Nature</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PORT__INTERACTION_NATURE = eINSTANCE.getPort_InteractionNature();

    /**
     * The meta object literal for the '{@link semcomdt.swarchitecture.cbse.impl.PassiveComponentImpl <em>Passive Component</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see semcomdt.swarchitecture.cbse.impl.PassiveComponentImpl
     * @see semcomdt.swarchitecture.cbse.impl.CbsePackageImpl#getPassiveComponent()
     * @generated
     */
    EClass PASSIVE_COMPONENT = eINSTANCE.getPassiveComponent();

    /**
     * The meta object literal for the '{@link semcomdt.swarchitecture.cbse.impl.ActiveComponentImpl <em>Active Component</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see semcomdt.swarchitecture.cbse.impl.ActiveComponentImpl
     * @see semcomdt.swarchitecture.cbse.impl.CbsePackageImpl#getActiveComponent()
     * @generated
     */
    EClass ACTIVE_COMPONENT = eINSTANCE.getActiveComponent();

    /**
     * The meta object literal for the '<em><b>Functions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTIVE_COMPONENT__FUNCTIONS = eINSTANCE.getActiveComponent_Functions();

    /**
     * The meta object literal for the '{@link semcomdt.swarchitecture.cbse.impl.FunctionImpl <em>Function</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see semcomdt.swarchitecture.cbse.impl.FunctionImpl
     * @see semcomdt.swarchitecture.cbse.impl.CbsePackageImpl#getFunction()
     * @generated
     */
    EClass FUNCTION = eINSTANCE.getFunction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCTION__NAME = eINSTANCE.getFunction_Name();

    /**
     * The meta object literal for the '{@link semcomdt.swarchitecture.cbse.impl.InteractionNatureImpl <em>Interaction Nature</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see semcomdt.swarchitecture.cbse.impl.InteractionNatureImpl
     * @see semcomdt.swarchitecture.cbse.impl.CbsePackageImpl#getInteractionNature()
     * @generated
     */
    EClass INTERACTION_NATURE = eINSTANCE.getInteractionNature();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTERACTION_NATURE__NAME = eINSTANCE.getInteractionNature_Name();

    /**
     * The meta object literal for the '{@link semcomdt.swarchitecture.cbse.impl.DataImpl <em>Data</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see semcomdt.swarchitecture.cbse.impl.DataImpl
     * @see semcomdt.swarchitecture.cbse.impl.CbsePackageImpl#getData()
     * @generated
     */
    EClass DATA = eINSTANCE.getData();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA__NAME = eINSTANCE.getData_Name();

    /**
     * The meta object literal for the '<em><b>Super Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATA__SUPER_TYPE = eINSTANCE.getData_SuperType();

    /**
     * The meta object literal for the '{@link semcomdt.swarchitecture.cbse.impl.DataTypeImpl <em>Data Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see semcomdt.swarchitecture.cbse.impl.DataTypeImpl
     * @see semcomdt.swarchitecture.cbse.impl.CbsePackageImpl#getDataType()
     * @generated
     */
    EClass DATA_TYPE = eINSTANCE.getDataType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_TYPE__NAME = eINSTANCE.getDataType_Name();

    /**
     * The meta object literal for the '{@link semcomdt.swarchitecture.cbse.impl.PayloadImpl <em>Payload</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see semcomdt.swarchitecture.cbse.impl.PayloadImpl
     * @see semcomdt.swarchitecture.cbse.impl.CbsePackageImpl#getPayload()
     * @generated
     */
    EClass PAYLOAD = eINSTANCE.getPayload();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PAYLOAD__NAME = eINSTANCE.getPayload_Name();

    /**
     * The meta object literal for the '{@link semcomdt.swarchitecture.cbse.impl.MsgExchangeImpl <em>Msg Exchange</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see semcomdt.swarchitecture.cbse.impl.MsgExchangeImpl
     * @see semcomdt.swarchitecture.cbse.impl.CbsePackageImpl#getMsgExchange()
     * @generated
     */
    EClass MSG_EXCHANGE = eINSTANCE.getMsgExchange();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MSG_EXCHANGE__NAME = eINSTANCE.getMsgExchange_Name();

    /**
     * The meta object literal for the '{@link semcomdt.swarchitecture.cbse.impl.CommunicationStyleImpl <em>Communication Style</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see semcomdt.swarchitecture.cbse.impl.CommunicationStyleImpl
     * @see semcomdt.swarchitecture.cbse.impl.CbsePackageImpl#getCommunicationStyle()
     * @generated
     */
    EClass COMMUNICATION_STYLE = eINSTANCE.getCommunicationStyle();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMUNICATION_STYLE__NAME = eINSTANCE.getCommunicationStyle_Name();

    /**
     * The meta object literal for the '{@link semcomdt.swarchitecture.cbse.PortKind <em>Port Kind</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see semcomdt.swarchitecture.cbse.PortKind
     * @see semcomdt.swarchitecture.cbse.impl.CbsePackageImpl#getPortKind()
     * @generated
     */
    EEnum PORT_KIND = eINSTANCE.getPortKind();

    /**
     * The meta object literal for the '{@link semcomdt.swarchitecture.cbse.ArchitectureElementType <em>Architecture Element Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see semcomdt.swarchitecture.cbse.ArchitectureElementType
     * @see semcomdt.swarchitecture.cbse.impl.CbsePackageImpl#getArchitectureElementType()
     * @generated
     */
    EEnum ARCHITECTURE_ELEMENT_TYPE = eINSTANCE.getArchitectureElementType();

  }

} //CbsePackage
