/**
 * generated by Xtext 2.35.0
 */
package semcomdt.swarchitecture.cbse;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Payload</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link semcomdt.swarchitecture.cbse.Payload#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see semcomdt.swarchitecture.cbse.CbsePackage#getPayload()
 * @model
 * @generated
 */
public interface Payload extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see semcomdt.swarchitecture.cbse.CbsePackage#getPayload_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link semcomdt.swarchitecture.cbse.Payload#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // Payload
