/**
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity.objective.ciaamps.ciaamps.impl;

import org.eclipse.emf.ecore.EClass;

import semcomdt.swsecurity.objective.ciaamps.ciaamps.CiaampsPackage;
import semcomdt.swsecurity.objective.ciaamps.ciaamps.SecurityProperty;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Security Property</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SecurityPropertyImpl extends AssetDetailsImpl implements SecurityProperty
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SecurityPropertyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CiaampsPackage.Literals.SECURITY_PROPERTY;
  }

} //SecurityPropertyImpl
