/*
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity.objective.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class CiaampsAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("semcomdt/swsecurity/objective/parser/antlr/internal/InternalCiaamps.tokens");
	}
}
