/**
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity.objective.ciaamps;

import semcomdt.swarchitecture.cbse.Element;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Asset</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link semcomdt.swsecurity.objective.ciaamps.Asset#getEnsureSP <em>Ensure SP</em>}</li>
 *   <li>{@link semcomdt.swsecurity.objective.ciaamps.Asset#getRefersToAE <em>Refers To AE</em>}</li>
 * </ul>
 *
 * @see semcomdt.swsecurity.objective.ciaamps.CiaampsPackage#getAsset()
 * @model
 * @generated
 */
public interface Asset extends AssetDetails
{
  /**
   * Returns the value of the '<em><b>Ensure SP</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ensure SP</em>' reference.
   * @see #setEnsureSP(SecurityProperty)
   * @see semcomdt.swsecurity.objective.ciaamps.CiaampsPackage#getAsset_EnsureSP()
   * @model
   * @generated
   */
  SecurityProperty getEnsureSP();

  /**
   * Sets the value of the '{@link semcomdt.swsecurity.objective.ciaamps.Asset#getEnsureSP <em>Ensure SP</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ensure SP</em>' reference.
   * @see #getEnsureSP()
   * @generated
   */
  void setEnsureSP(SecurityProperty value);

  /**
   * Returns the value of the '<em><b>Refers To AE</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Refers To AE</em>' reference.
   * @see #setRefersToAE(Element)
   * @see semcomdt.swsecurity.objective.ciaamps.CiaampsPackage#getAsset_RefersToAE()
   * @model
   * @generated
   */
  Element getRefersToAE();

  /**
   * Sets the value of the '{@link semcomdt.swsecurity.objective.ciaamps.Asset#getRefersToAE <em>Refers To AE</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Refers To AE</em>' reference.
   * @see #getRefersToAE()
   * @generated
   */
  void setRefersToAE(Element value);

} // Asset
