/**
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity.objective.ciaamps;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Asset Details</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link semcomdt.swsecurity.objective.ciaamps.AssetDetails#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see semcomdt.swsecurity.objective.ciaamps.CiaampsPackage#getAssetDetails()
 * @model
 * @generated
 */
public interface AssetDetails extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see semcomdt.swsecurity.objective.ciaamps.CiaampsPackage#getAssetDetails_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link semcomdt.swsecurity.objective.ciaamps.AssetDetails#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // AssetDetails
