/**
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity.objective.ciaamps;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see semcomdt.swsecurity.objective.ciaamps.CiaampsPackage
 * @generated
 */
public interface CiaampsFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CiaampsFactory eINSTANCE = semcomdt.swsecurity.objective.ciaamps.impl.CiaampsFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Assets</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Assets</em>'.
   * @generated
   */
  Assets createAssets();

  /**
   * Returns a new object of class '<em>Import</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Import</em>'.
   * @generated
   */
  Import createImport();

  /**
   * Returns a new object of class '<em>Asset Details</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Asset Details</em>'.
   * @generated
   */
  AssetDetails createAssetDetails();

  /**
   * Returns a new object of class '<em>Property Category</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Property Category</em>'.
   * @generated
   */
  PropertyCategory createPropertyCategory();

  /**
   * Returns a new object of class '<em>Security Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Security Property</em>'.
   * @generated
   */
  SecurityProperty createSecurityProperty();

  /**
   * Returns a new object of class '<em>Asset</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Asset</em>'.
   * @generated
   */
  Asset createAsset();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  CiaampsPackage getCiaampsPackage();

} //CiaampsFactory
