/**
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity.objective.ciaamps;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see semcomdt.swsecurity.objective.ciaamps.CiaampsFactory
 * @model kind="package"
 * @generated
 */
public interface CiaampsPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "ciaamps";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.semcomdt.swsecurity/objective/Ciaamps";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "ciaamps";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CiaampsPackage eINSTANCE = semcomdt.swsecurity.objective.ciaamps.impl.CiaampsPackageImpl.init();

  /**
   * The meta object id for the '{@link semcomdt.swsecurity.objective.ciaamps.impl.AssetsImpl <em>Assets</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see semcomdt.swsecurity.objective.ciaamps.impl.AssetsImpl
   * @see semcomdt.swsecurity.objective.ciaamps.impl.CiaampsPackageImpl#getAssets()
   * @generated
   */
  int ASSETS = 0;

  /**
   * The feature id for the '<em><b>Imports</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSETS__IMPORTS = 0;

  /**
   * The feature id for the '<em><b>Assets</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSETS__ASSETS = 1;

  /**
   * The number of structural features of the '<em>Assets</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSETS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link semcomdt.swsecurity.objective.ciaamps.impl.ImportImpl <em>Import</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see semcomdt.swsecurity.objective.ciaamps.impl.ImportImpl
   * @see semcomdt.swsecurity.objective.ciaamps.impl.CiaampsPackageImpl#getImport()
   * @generated
   */
  int IMPORT = 1;

  /**
   * The feature id for the '<em><b>Import URI</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT__IMPORT_URI = 0;

  /**
   * The number of structural features of the '<em>Import</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link semcomdt.swsecurity.objective.ciaamps.impl.AssetDetailsImpl <em>Asset Details</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see semcomdt.swsecurity.objective.ciaamps.impl.AssetDetailsImpl
   * @see semcomdt.swsecurity.objective.ciaamps.impl.CiaampsPackageImpl#getAssetDetails()
   * @generated
   */
  int ASSET_DETAILS = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSET_DETAILS__NAME = 0;

  /**
   * The number of structural features of the '<em>Asset Details</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSET_DETAILS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link semcomdt.swsecurity.objective.ciaamps.impl.PropertyCategoryImpl <em>Property Category</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see semcomdt.swsecurity.objective.ciaamps.impl.PropertyCategoryImpl
   * @see semcomdt.swsecurity.objective.ciaamps.impl.CiaampsPackageImpl#getPropertyCategory()
   * @generated
   */
  int PROPERTY_CATEGORY = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_CATEGORY__NAME = ASSET_DETAILS__NAME;

  /**
   * The feature id for the '<em><b>Secprop</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_CATEGORY__SECPROP = ASSET_DETAILS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Property Category</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_CATEGORY_FEATURE_COUNT = ASSET_DETAILS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link semcomdt.swsecurity.objective.ciaamps.impl.SecurityPropertyImpl <em>Security Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see semcomdt.swsecurity.objective.ciaamps.impl.SecurityPropertyImpl
   * @see semcomdt.swsecurity.objective.ciaamps.impl.CiaampsPackageImpl#getSecurityProperty()
   * @generated
   */
  int SECURITY_PROPERTY = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECURITY_PROPERTY__NAME = ASSET_DETAILS__NAME;

  /**
   * The number of structural features of the '<em>Security Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECURITY_PROPERTY_FEATURE_COUNT = ASSET_DETAILS_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link semcomdt.swsecurity.objective.ciaamps.impl.AssetImpl <em>Asset</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see semcomdt.swsecurity.objective.ciaamps.impl.AssetImpl
   * @see semcomdt.swsecurity.objective.ciaamps.impl.CiaampsPackageImpl#getAsset()
   * @generated
   */
  int ASSET = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSET__NAME = ASSET_DETAILS__NAME;

  /**
   * The feature id for the '<em><b>Ensure SP</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSET__ENSURE_SP = ASSET_DETAILS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Refers To AE</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSET__REFERS_TO_AE = ASSET_DETAILS_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Asset</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSET_FEATURE_COUNT = ASSET_DETAILS_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link semcomdt.swsecurity.objective.ciaamps.Assets <em>Assets</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Assets</em>'.
   * @see semcomdt.swsecurity.objective.ciaamps.Assets
   * @generated
   */
  EClass getAssets();

  /**
   * Returns the meta object for the containment reference list '{@link semcomdt.swsecurity.objective.ciaamps.Assets#getImports <em>Imports</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Imports</em>'.
   * @see semcomdt.swsecurity.objective.ciaamps.Assets#getImports()
   * @see #getAssets()
   * @generated
   */
  EReference getAssets_Imports();

  /**
   * Returns the meta object for the containment reference list '{@link semcomdt.swsecurity.objective.ciaamps.Assets#getAssets <em>Assets</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Assets</em>'.
   * @see semcomdt.swsecurity.objective.ciaamps.Assets#getAssets()
   * @see #getAssets()
   * @generated
   */
  EReference getAssets_Assets();

  /**
   * Returns the meta object for class '{@link semcomdt.swsecurity.objective.ciaamps.Import <em>Import</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Import</em>'.
   * @see semcomdt.swsecurity.objective.ciaamps.Import
   * @generated
   */
  EClass getImport();

  /**
   * Returns the meta object for the attribute '{@link semcomdt.swsecurity.objective.ciaamps.Import#getImportURI <em>Import URI</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Import URI</em>'.
   * @see semcomdt.swsecurity.objective.ciaamps.Import#getImportURI()
   * @see #getImport()
   * @generated
   */
  EAttribute getImport_ImportURI();

  /**
   * Returns the meta object for class '{@link semcomdt.swsecurity.objective.ciaamps.AssetDetails <em>Asset Details</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Asset Details</em>'.
   * @see semcomdt.swsecurity.objective.ciaamps.AssetDetails
   * @generated
   */
  EClass getAssetDetails();

  /**
   * Returns the meta object for the attribute '{@link semcomdt.swsecurity.objective.ciaamps.AssetDetails#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see semcomdt.swsecurity.objective.ciaamps.AssetDetails#getName()
   * @see #getAssetDetails()
   * @generated
   */
  EAttribute getAssetDetails_Name();

  /**
   * Returns the meta object for class '{@link semcomdt.swsecurity.objective.ciaamps.PropertyCategory <em>Property Category</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Property Category</em>'.
   * @see semcomdt.swsecurity.objective.ciaamps.PropertyCategory
   * @generated
   */
  EClass getPropertyCategory();

  /**
   * Returns the meta object for the containment reference list '{@link semcomdt.swsecurity.objective.ciaamps.PropertyCategory#getSecprop <em>Secprop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Secprop</em>'.
   * @see semcomdt.swsecurity.objective.ciaamps.PropertyCategory#getSecprop()
   * @see #getPropertyCategory()
   * @generated
   */
  EReference getPropertyCategory_Secprop();

  /**
   * Returns the meta object for class '{@link semcomdt.swsecurity.objective.ciaamps.SecurityProperty <em>Security Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Security Property</em>'.
   * @see semcomdt.swsecurity.objective.ciaamps.SecurityProperty
   * @generated
   */
  EClass getSecurityProperty();

  /**
   * Returns the meta object for class '{@link semcomdt.swsecurity.objective.ciaamps.Asset <em>Asset</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Asset</em>'.
   * @see semcomdt.swsecurity.objective.ciaamps.Asset
   * @generated
   */
  EClass getAsset();

  /**
   * Returns the meta object for the reference '{@link semcomdt.swsecurity.objective.ciaamps.Asset#getEnsureSP <em>Ensure SP</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ensure SP</em>'.
   * @see semcomdt.swsecurity.objective.ciaamps.Asset#getEnsureSP()
   * @see #getAsset()
   * @generated
   */
  EReference getAsset_EnsureSP();

  /**
   * Returns the meta object for the reference '{@link semcomdt.swsecurity.objective.ciaamps.Asset#getRefersToAE <em>Refers To AE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Refers To AE</em>'.
   * @see semcomdt.swsecurity.objective.ciaamps.Asset#getRefersToAE()
   * @see #getAsset()
   * @generated
   */
  EReference getAsset_RefersToAE();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  CiaampsFactory getCiaampsFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link semcomdt.swsecurity.objective.ciaamps.impl.AssetsImpl <em>Assets</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see semcomdt.swsecurity.objective.ciaamps.impl.AssetsImpl
     * @see semcomdt.swsecurity.objective.ciaamps.impl.CiaampsPackageImpl#getAssets()
     * @generated
     */
    EClass ASSETS = eINSTANCE.getAssets();

    /**
     * The meta object literal for the '<em><b>Imports</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSETS__IMPORTS = eINSTANCE.getAssets_Imports();

    /**
     * The meta object literal for the '<em><b>Assets</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSETS__ASSETS = eINSTANCE.getAssets_Assets();

    /**
     * The meta object literal for the '{@link semcomdt.swsecurity.objective.ciaamps.impl.ImportImpl <em>Import</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see semcomdt.swsecurity.objective.ciaamps.impl.ImportImpl
     * @see semcomdt.swsecurity.objective.ciaamps.impl.CiaampsPackageImpl#getImport()
     * @generated
     */
    EClass IMPORT = eINSTANCE.getImport();

    /**
     * The meta object literal for the '<em><b>Import URI</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMPORT__IMPORT_URI = eINSTANCE.getImport_ImportURI();

    /**
     * The meta object literal for the '{@link semcomdt.swsecurity.objective.ciaamps.impl.AssetDetailsImpl <em>Asset Details</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see semcomdt.swsecurity.objective.ciaamps.impl.AssetDetailsImpl
     * @see semcomdt.swsecurity.objective.ciaamps.impl.CiaampsPackageImpl#getAssetDetails()
     * @generated
     */
    EClass ASSET_DETAILS = eINSTANCE.getAssetDetails();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASSET_DETAILS__NAME = eINSTANCE.getAssetDetails_Name();

    /**
     * The meta object literal for the '{@link semcomdt.swsecurity.objective.ciaamps.impl.PropertyCategoryImpl <em>Property Category</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see semcomdt.swsecurity.objective.ciaamps.impl.PropertyCategoryImpl
     * @see semcomdt.swsecurity.objective.ciaamps.impl.CiaampsPackageImpl#getPropertyCategory()
     * @generated
     */
    EClass PROPERTY_CATEGORY = eINSTANCE.getPropertyCategory();

    /**
     * The meta object literal for the '<em><b>Secprop</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTY_CATEGORY__SECPROP = eINSTANCE.getPropertyCategory_Secprop();

    /**
     * The meta object literal for the '{@link semcomdt.swsecurity.objective.ciaamps.impl.SecurityPropertyImpl <em>Security Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see semcomdt.swsecurity.objective.ciaamps.impl.SecurityPropertyImpl
     * @see semcomdt.swsecurity.objective.ciaamps.impl.CiaampsPackageImpl#getSecurityProperty()
     * @generated
     */
    EClass SECURITY_PROPERTY = eINSTANCE.getSecurityProperty();

    /**
     * The meta object literal for the '{@link semcomdt.swsecurity.objective.ciaamps.impl.AssetImpl <em>Asset</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see semcomdt.swsecurity.objective.ciaamps.impl.AssetImpl
     * @see semcomdt.swsecurity.objective.ciaamps.impl.CiaampsPackageImpl#getAsset()
     * @generated
     */
    EClass ASSET = eINSTANCE.getAsset();

    /**
     * The meta object literal for the '<em><b>Ensure SP</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSET__ENSURE_SP = eINSTANCE.getAsset_EnsureSP();

    /**
     * The meta object literal for the '<em><b>Refers To AE</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSET__REFERS_TO_AE = eINSTANCE.getAsset_RefersToAE();

  }

} //CiaampsPackage
