/**
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity.objective.ciaamps;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property Category</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link semcomdt.swsecurity.objective.ciaamps.PropertyCategory#getSecprop <em>Secprop</em>}</li>
 * </ul>
 *
 * @see semcomdt.swsecurity.objective.ciaamps.CiaampsPackage#getPropertyCategory()
 * @model
 * @generated
 */
public interface PropertyCategory extends AssetDetails
{
  /**
   * Returns the value of the '<em><b>Secprop</b></em>' containment reference list.
   * The list contents are of type {@link semcomdt.swsecurity.objective.ciaamps.SecurityProperty}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Secprop</em>' containment reference list.
   * @see semcomdt.swsecurity.objective.ciaamps.CiaampsPackage#getPropertyCategory_Secprop()
   * @model containment="true"
   * @generated
   */
  EList<SecurityProperty> getSecprop();

} // PropertyCategory
