/*
 * generated by Xtext 2.35.0
 */
package semcomdt.swarchitecture.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCbseScopeProvider extends DelegatingScopeProvider {
}
