/*
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity.objective.ciaamps.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import semcomdt.swsecurity.objective.ciaamps.parser.antlr.internal.InternalCiaampsParser;
import semcomdt.swsecurity.objective.ciaamps.services.CiaampsGrammarAccess;

public class CiaampsParser extends AbstractAntlrParser {

	@Inject
	private CiaampsGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCiaampsParser createParser(XtextTokenStream stream) {
		return new InternalCiaampsParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Assets";
	}

	public CiaampsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CiaampsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
