/*
 * generated by Xtext 2.35.0
 */
package semcomdt.swarchitecture;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CbseRuntimeModule extends AbstractCbseRuntimeModule {
}
