/**
 * generated by Xtext 2.35.0
 */
package semcomdt.swarchitecture.cbse.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EDataType;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import semcomdt.swarchitecture.cbse.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class CbseFactoryImpl extends EFactoryImpl implements CbseFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static CbseFactory init()
  {
    try
    {
      CbseFactory theCbseFactory = (CbseFactory)EPackage.Registry.INSTANCE.getEFactory(CbsePackage.eNS_URI);
      if (theCbseFactory != null)
      {
        return theCbseFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new CbseFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CbseFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case CbsePackage.CBSE: return createCbse();
      case CbsePackage.ELEMENT: return createElement();
      case CbsePackage.COMPONENT: return createComponent();
      case CbsePackage.CONNECTOR: return createConnector();
      case CbsePackage.PORT: return createPort();
      case CbsePackage.PASSIVE_COMPONENT: return createPassiveComponent();
      case CbsePackage.ACTIVE_COMPONENT: return createActiveComponent();
      case CbsePackage.FUNCTION: return createFunction();
      case CbsePackage.INTERACTION_NATURE: return createInteractionNature();
      case CbsePackage.DATA: return createData();
      case CbsePackage.DATA_TYPE: return createDataType();
      case CbsePackage.PAYLOAD: return createPayload();
      case CbsePackage.MSG_EXCHANGE: return createMsgExchange();
      case CbsePackage.COMMUNICATION_STYLE: return createCommunicationStyle();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object createFromString(EDataType eDataType, String initialValue)
  {
    switch (eDataType.getClassifierID())
    {
      case CbsePackage.PORT_KIND:
        return createPortKindFromString(eDataType, initialValue);
      case CbsePackage.ARCHITECTURE_ELEMENT_TYPE:
        return createArchitectureElementTypeFromString(eDataType, initialValue);
      default:
        throw new IllegalArgumentException("The datatype '" + eDataType.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String convertToString(EDataType eDataType, Object instanceValue)
  {
    switch (eDataType.getClassifierID())
    {
      case CbsePackage.PORT_KIND:
        return convertPortKindToString(eDataType, instanceValue);
      case CbsePackage.ARCHITECTURE_ELEMENT_TYPE:
        return convertArchitectureElementTypeToString(eDataType, instanceValue);
      default:
        throw new IllegalArgumentException("The datatype '" + eDataType.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Cbse createCbse()
  {
    CbseImpl cbse = new CbseImpl();
    return cbse;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Element createElement()
  {
    ElementImpl element = new ElementImpl();
    return element;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Component createComponent()
  {
    ComponentImpl component = new ComponentImpl();
    return component;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Connector createConnector()
  {
    ConnectorImpl connector = new ConnectorImpl();
    return connector;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Port createPort()
  {
    PortImpl port = new PortImpl();
    return port;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PassiveComponent createPassiveComponent()
  {
    PassiveComponentImpl passiveComponent = new PassiveComponentImpl();
    return passiveComponent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ActiveComponent createActiveComponent()
  {
    ActiveComponentImpl activeComponent = new ActiveComponentImpl();
    return activeComponent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Function createFunction()
  {
    FunctionImpl function = new FunctionImpl();
    return function;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public InteractionNature createInteractionNature()
  {
    InteractionNatureImpl interactionNature = new InteractionNatureImpl();
    return interactionNature;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Data createData()
  {
    DataImpl data = new DataImpl();
    return data;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DataType createDataType()
  {
    DataTypeImpl dataType = new DataTypeImpl();
    return dataType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Payload createPayload()
  {
    PayloadImpl payload = new PayloadImpl();
    return payload;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MsgExchange createMsgExchange()
  {
    MsgExchangeImpl msgExchange = new MsgExchangeImpl();
    return msgExchange;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CommunicationStyle createCommunicationStyle()
  {
    CommunicationStyleImpl communicationStyle = new CommunicationStyleImpl();
    return communicationStyle;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PortKind createPortKindFromString(EDataType eDataType, String initialValue)
  {
    PortKind result = PortKind.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertPortKindToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ArchitectureElementType createArchitectureElementTypeFromString(EDataType eDataType, String initialValue)
  {
    ArchitectureElementType result = ArchitectureElementType.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertArchitectureElementTypeToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CbsePackage getCbsePackage()
  {
    return (CbsePackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static CbsePackage getPackage()
  {
    return CbsePackage.eINSTANCE;
  }

} //CbseFactoryImpl
