/**
 * generated by Xtext 2.35.0
 */
package semcomdt.swarchitecture.cbse.impl;

import org.eclipse.emf.ecore.EClass;

import semcomdt.swarchitecture.cbse.CbsePackage;
import semcomdt.swarchitecture.cbse.Component;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Component</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ComponentImpl extends ElementImpl implements Component
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ComponentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CbsePackage.Literals.COMPONENT;
  }

} //ComponentImpl
