/**
 * generated by Xtext 2.35.0
 */
package semcomdt.swarchitecture.cbse.impl;

import org.eclipse.emf.ecore.EClass;

import semcomdt.swarchitecture.cbse.CbsePackage;
import semcomdt.swarchitecture.cbse.Connector;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Connector</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ConnectorImpl extends ElementImpl implements Connector
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConnectorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CbsePackage.Literals.CONNECTOR;
  }

} //ConnectorImpl
