/*
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity.ui.labeling;

import com.google.inject.Inject;

import semcomdt.swsecurity.ssrt.SolutionTree;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
public class SsrtLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public SsrtLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	// Labels and icons can be computed like this:
	
//	String text(SolutionTree soltree) {
//		return "A greeting to " + soltree.getName();
//	}
//
//	String image(Greeting ele) {
//		return "Greeting.gif";
//	}
}
