/*
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity.web;

import org.eclipse.xtext.web.server.generator.IContentTypeProvider;
import org.eclipse.xtext.web.server.model.IWebResourceSetProvider;
import org.eclipse.xtext.web.server.persistence.FileResourceHandler;
import org.eclipse.xtext.web.server.persistence.IResourceBaseProvider;
import org.eclipse.xtext.web.server.persistence.IServerResourceHandler;

import com.google.inject.Binder;

import semcomdt.swsecurity.web.resource.SsrtContentTypeProvider;
import semcomdt.swsecurity.web.resource.SsrtResourceSetProvider;

/**
 * Use this class to register additional components to be used within the web application.
 */
public class SsrtWebModule extends AbstractSsrtWebModule {
	private IResourceBaseProvider resourceBaseProvider;
	@Override
	public Class<? extends IContentTypeProvider> bindIContentTypeProvider() {
		return SsrtContentTypeProvider.class;
	}

	public Class<? extends IWebResourceSetProvider> bindIWebResourceSetProvider() {
		return SsrtResourceSetProvider.class;
	}

	public void configureResourceBaseProvider(Binder binder) {
		if (resourceBaseProvider != null) {
			binder.bind(IResourceBaseProvider.class).toInstance(resourceBaseProvider);
		}
	}

	public Class<? extends IServerResourceHandler> bindIServerResourceHandler() {
		return FileResourceHandler.class;
	}

	public SsrtWebModule(IResourceBaseProvider resourceBaseProvider) {
		this.resourceBaseProvider = resourceBaseProvider;
	}

	
}
