/*
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity.web;

import org.eclipse.xtext.util.Modules2;
import org.eclipse.xtext.web.server.persistence.IResourceBaseProvider;

import com.google.inject.Guice;
import com.google.inject.Injector;

import semcomdt.swsecurity.SsrtStandaloneSetup;
import semcomdt.swsecurity.ide.SsrtIdeModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class SsrtWebSetup extends SsrtStandaloneSetup {
	private final IResourceBaseProvider resourceBaseProvider;
//	private final IResourceServiceProvider resourceServiceProvider;

//	public SsrtWebSetup(IResourceBaseProvider resourceBaseProvider, IResourceServiceProvider resourceServiceProvider) {
//		this.resourceBaseProvider = resourceBaseProvider;
//		this.resourceServiceProvider = resourceServiceProvider;
//	}

	public SsrtWebSetup(IResourceBaseProvider resourceBaseProvider) {
		this.resourceBaseProvider = resourceBaseProvider;
	}

	@Override
	public Injector createInjector() {
		SsrtWebModule webmodule = new SsrtWebModule(this.resourceBaseProvider);

		return Guice.createInjector(Modules2.mixin(new SsrtRuntimeWebModule(), new SsrtIdeModule(), webmodule));
	}

}
