/*
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity.web;

import org.eclipse.xtext.web.server.persistence.FileResourceHandler;
import org.eclipse.xtext.web.server.persistence.IResourceBaseProvider;
import org.eclipse.xtext.web.server.persistence.IServerResourceHandler;

import com.google.inject.Binder;

/**
 * Use this class to register additional components to be used within the web application.
 */
public class SsrtWebModule extends AbstractSsrtWebModule {
//	private IResourceBaseProvider resourceBaseProvider;
//
//	public Class<? extends IServerResourceHandler> bindIServerResourceHandler() {
//		return FileResourceHandler.class;
//	}
//
//	public void configureResourceBaseProvider(Binder binder) {
//		if (resourceBaseProvider != null) {
//			binder.bind(IResourceBaseProvider.class).toInstance(this.resourceBaseProvider);
//		}
//	}
//
//	public IResourceBaseProvider getResourceBaseProvider() {
//		return resourceBaseProvider;
//	}
//
//	public void setResourceBaseProvider(IResourceBaseProvider resourceBaseProvider) {
//		this.resourceBaseProvider = resourceBaseProvider;
//	}
	
}
